### ISSUE TITLE
[RFC] Language list - INNO-1321

### ISSUE THREAD

**Issue by yhuard** [ec-europa/europa-component-library#1003]
## Current implementation

In our current implementation, links look like this:

```html 
<a href="/example#language_ga" class="ecl-language-list__link ecl-link ecl-link--standalone">Gaeilge</a>
```

## What can we improve?

Obviously, 2 attributes are missing:
- `lang`: because "Gaeilge" is not in English (the language of the document)
- `hreflang`: because the link points to a page which is not in English

One third attribute can be discussed:
- `rel="alternate"`: 

> When used in combination with the `hreflang` attribute (with a value other than that of the document itself), rel="alternate" means a link to **a version of the current document**, but in the language indicated by the hreflang attribute.

— http://microformats.org/wiki/rel-alternate

To me, we should use this attribute in the "overlay language list", where links point to the same page in another language.
It should not be used in the "splash page language list", where links point to a completely different document than the current one. It seems to me that https://ec.europa.eu/info/ misuses the `rel="alternate"` attribute.

- Are we all on the same page here? 
- Are there any other attributes we could or should use?

**Comment by emeryro** [comment]
Most SEO examples I see use `hreflang` in a `<link>` tag (in the `<head>`), but indeed it is valid in a `<a>` tag too (even if not widely used). I wonder if we shouldn't enforce the use of `<link>` instead...

`rel="alternate"` seems indeed fine for overlay (but again, it is commonly used in `<link>`)
 
But the `lang` parameter doesn't seems to be valid here. It isn't listed in allowed parameters
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
https://www.w3schools.com/tags/tag_a.asp

**Comment by yhuard** [comment]
> even if not widely used

what does make you think that?

> I wonder if we shouldn't enforce the use of `<link>` instead...

instead of `<a>`? 🤔 

> But the `lang` parameter doesn't seems to be valid here.

> Global Attributes
> The `<a>` tag also supports the Global Attributes in HTML.

— https://www.w3schools.com/tags/tag_a.asp 

-> https://www.w3schools.com/tags/ref_standardattributes.asp 😃

**Comment by emeryro** [comment]
> what does make you think that?

Just the fact that almost all articles concerning `hreflang` I find uses `<link>` and I really have to specifically search for usage in `<a>` to find some.

Ok for the `lang`

**Comment by emeryro** [comment]
To move forward on this topic, we can indeed add `hreflang`, `lang` and `rel="alternate"` (overlay only) to the `a`, as it is part of the component.
We won't manage the `<link>` in header anyway, except maybe in templates.

**Comment by yhuard** [comment]
If we had a `SEO: best practices` section, we could mention the `<link rel="alternate" href="..." hreflang="..." />`, it would be a nice addition. 👍 But isn't it out of the scope of the design system? Here are discussing how to make websites 😆

**Comment by degliwe** [comment]
All good for me.

**Comment by yhuard** [comment]
It looks like we have a deal.

Next steps:
- upgrade the links in the `language list` component with the `lang` and `hreflang` attributes
- use `rel="alternate"` on the overlay variant only
