### ISSUE TITLE
Proposal: bring back right pointing chevron

### ISSUE THREAD

**Issue by daniel-tudor** [ec-europa/europa-component-library#1049]
### Expected behavior
In ECL v1 there was a call to action button with a right pointing arrow. It's common practice because it clearly indicates to users that the button points to a page when clicked.
![Illustrator_2019-03-21_17-32-58](https://user-images.githubusercontent.com/8298325/54810749-26659c00-4c87-11e9-9b0d-441609c0fd11.png)

### Actual behavior
Currently there is no possibility to add such an icon on a button anymore.
![2019-03-21_17-32-15](https://user-images.githubusercontent.com/8298325/54810750-26659c00-4c87-11e9-959d-527eaa06b7a5.png)

### Steps to reproduce the issue
I noticed this while playing with the button Icon (sample) knob here: https://ecl-twig.netlify.com/ec/?path=/story/components-button--call-to-action

This icon would be a good addition to the list of existing icons and definitely make a difference on call-to-action buttons.

**Comment by yhuard** [comment]
Hi @daniel-tudor 

Actually, you can use any icon from the [iconography](https://v2--europa-component-library.netlify.com/ec/guidelines/iconography/) on the button, including "corner-arrow" which is the one you're looking for. You'll also want to rotate it, as it's explained on the [icon component's page](https://v2--europa-component-library.netlify.com/ec/components/icon/code/). 

The ECL 2 documentation shows an example of the CTA button with the icon: https://v2--europa-component-library.netlify.com/ec/components/button/code/ 😉 

Are you using ECL Twig components? We have another repository for questions related to ECL Twig: https://github.com/ec-europa/ecl-twig/

**Comment by daniel-tudor** [comment]
Thanks a lot, @yhuard , I didn't know about the rotation. I guess I need to study a bit more.
Indeed, I was checking on ECL Twig
