### ISSUE TITLE
Width of label in field component on small viewport

### ISSUE THREAD

**Issue by alessandro-russo** [ec-europa/europa-component-library#1055]
### Expected behavior
In **ECL v1** (latest 1.4.0), the width of the label (`ecl-field__label`) of the **field** component should be limited to 20% when `@media (min-width: 768px)` only (in line with the other rules that define the appearance of `ecl-field` and `ecl-field__label`).

### Actual behavior
The width of the label is *always* limited to 20%.
On small screens, when the label text exceeds this width, the text unnecessarily wraps (in my opinion).

### Steps to reproduce the issue
"Quick-and-dirty" way:
* open the [demo preview](https://v1--europa-component-library.netlify.com/ec/components/preview/ec-component-field) and replace the label in the example (**Name**) with a longer label (e.g., **Longer label**);
* reduce the viewport (e.g., < 400) to see the label text wrapping (see picture for an example)

<img width="490" alt="field-label" src="https://user-images.githubusercontent.com/26624967/55082861-ba2dd280-50a2-11e9-8e52-93d2915b4aa2.png">

Thanks!!!

**Comment by emeryro** [comment]
Hello,
Thanks for your feedback

Indeed, display isn't correct on small screen. There is no reason not to take the full width here.
A ticket has been created in our board to handle that: https://webgate.ec.europa.eu/CITnet/jira/browse/INNO-1421

**Comment by emeryro** [comment]
Issue has been fixed, it will be deployed with next release
