### ISSUE TITLE
ECL v1 - No scroll on language list on small viewport

### ISSUE THREAD

**Issue by alessandro-russo** [ec-europa/europa-component-library#1088]
### ECL version
v1.x (latest: 1.8.0)

### Expected behavior
On small screens (`< 480px`), it should be possible to scroll through the list of languages that appears when clicking the language selector (site level) in the header.

### Actual behavior
The list of languages that appears in the dialog cannot be scrolled (`overflow: auto` on `.ecl-dialog--wide` is present only when `min-width: 480px`).

### Steps to reproduce the issue
From the [site header](https://v1--europa-component-library.netlify.com/ec/components/preview/ec-component-site-header) demo page, with a viewport width < 480px, click on the language selector and try to scroll down through the language list.

---

Thanks for your support!

**Comment by yhuard** [comment]
Hi @alessandro-russo 

Thank you for reporting this issue! I have to double check it, there might have been a reason why we only added the overflow when `min-width: 480px`, or it might just be a mistake... I'll keep you posted.

**Comment by yhuard** [comment]
Hi @alessandro-russo 

A patch has been merged today. A new release of ECL v1 will be made next week probably.

Thanks again for reporting this issue!

**Comment by alessandro-russo** [comment]
Hi @yhuard,

thanks to you and your colleagues for taking care of this!

**Comment by yhuard** [comment]
[ECL 1.9.0](https://github.com/ec-europa/europa-component-library/releases/tag/v1.9.0) has been released. It contains the patch. Thanks again for reporting the issue 🍻
