### ISSUE TITLE
Advise on creating staff member pages

### ISSUE THREAD

**Issue by daniel-tudor** [ec-europa/europa-component-library#1092]
Dear all,

Could you please advise on what ECL component(s) to use for designing a staff member page?

### Expected behavior
For EuroHPC website we need to be able to display staff pages similar to this one: https://www.ecsel.eu/team/bert-de-colvenaer. We need to be able to display: name, photo, CV file, position and some bio text.

### Actual behavior
I wasn't able to identify any component combination that could render this information in a structured way. Sure, we could easily combine an image with a text paragraph, but then the user experience will be less than optimal.

### Steps to reproduce the issue
-

Thanks for your help

**Comment by yhuard** [comment]
Hi @daniel-tudor 

I've forwarded your question to the design team, I hope to hear from them soon.
Meanwhile, can you confirm that you're using ECL v2, right? Not ECL v1?

Thanks

**Comment by daniel-tudor** [comment]
Thanks, @yhuard , 

I was referring to ECL v1, since OpenEuropa didn't implement ECL v2 yet and we will use OpenEuropa for our project.

**Comment by kevinambrogi1** [comment]
Hi @daniel-tudor,
Open Europa should implement ECL v2 very soon (a matter of weeks), so depending on how soon you start your project, you might be using either ECL v1 or v2. 
We will provide you the best fit for both to make sure that you are covered in any case. Thanks!

**Comment by yhuard** [comment]
Hi @daniel-tudor 

Thank you for the precision.
A new ticket has been created: https://webgate.ec.europa.eu/CITnet/jira/browse/WEBRAT-9064
I hope you'll get an answer soon :)

**Comment by gillesdeudon** [comment]
Hello @kevinambrogi1,

I am facing to the same question. Any news about this topic?

Regards.
Gilles
