### ISSUE TITLE
Site switchers in ECL v2 not available?

### ISSUE THREAD

**Issue by df-git** [ec-europa/europa-component-library#1249]
Dear all,
I am looking for the "Site switchers" (the one with the links "Commission and its priorities" and "Policies, information and services") top bar that are available in the current EC websites and in the ECL V1. Is it available for the ECL V2?

**Comment by Yaomimi** [comment]
https://ec.europa.eu/newsroom/cem/item-detail.cfm?item_id=655992&newsletter_id=602&utm_source=cem_newsletter&utm_medium=email&utm_campaign=Info%20site%20updates,%20new%20featur&utm_content=Europa%20Support%20-%20Homepage%20merge%20and%20Global%20Banner%20GLOBAN%20%20notice%20on%20futu&lang=en

**Comment by df-git** [comment]
Thank you
