### ISSUE TITLE
Navigation > Menus missing in ECL v2

### ISSUE THREAD

**Issue by df-git** [ec-europa/europa-component-library#1279]
Dear All,
I've noticed that in the ECL  v2 the menus are missing (like the light blue menu bar available in the ECL v1 - https://v1--europa-component-library.netlify.com/ec/components/detail/ec-component-navigation-menu).

Are you planning to add it also to the ECL v2?
Is there a way with the current version to create a menu like the one mentioned above?

**Comment by yhuard** [comment]
Hi!

This is a sensitive question... 

The UX team is working on it. Hopefully, a new navigation system will come soon.

Unofficially, there is a port of the ECL 1 component: https://ec.europa.eu/component-library/ec/components/navigation/menu-legacy/usage/ It only works with the "legacy" preset (see https://www.npmjs.com/package/@ecl/ec-preset-legacy/v/2.10.1 or https://www.npmjs.com/package/@ecl/ec-preset-legacy-website/v/2.10.1). Again, it's not officially supported, we won't maintain it. It's only a temporary solution for those who need it and can't afford to wait for the new system to be available. Use at your own risk.

**Comment by df-git** [comment]
Thank you
