### ISSUE TITLE
ECL v2.10.1 - Icon margin/spacing - Inconsistencies between the HTML code and the examples

### ISSUE THREAD

**Issue by df-git** [ec-europa/europa-component-library#1283]
Dear All,
We are trying to integrate the new ECL in our website. 
When we copy/paste the html from the guide available here:

- https://ec.europa.eu/component-library/ec/getting-started/
- https://ec.europa.eu/component-library/ec/templates/pages/campaign/code/

we notice some problems with the icon margin.  In the example available here https://ec.europa.eu/component-library/playground/ec/iframe.html?id=templates-pages--campaign the icons have the space before/after the text. But in the HTML rendered by exactly copy-pasting the code from the guide, the space are missing:

![Capture](https://user-images.githubusercontent.com/29379252/63843904-74de3b80-c987-11e9-8e2e-9a3628e76052.JPG)

Can you please help us with this issue?

**Comment by yhuard** [comment]
Hi!

Actually, there's a `&nbsp;` between the logo and the label:

![image](https://user-images.githubusercontent.com/3524389/63851092-d7d6cf00-c995-11e9-9bed-f0b9b1d125c0.png)

It seems that our code beautifier strips it out... I will try to find a solution to fix the code displayed on the website. In the meantime, you can already fix your issue by adding the missing `&nbsp;` 😃

**Comment by df-git** [comment]
Thank you for your support!
