### ISSUE TITLE
Possible improvements on the table

### ISSUE THREAD

**Issue by emanuelaepure** [ec-europa/europa-component-library#1300]
Is it possible to improve the table by adding a search box and the possibility to order the columns?

**Comment by emanuelaepure** [comment]
Hi guys,

Do you have anynews on this?

Thank you

**Comment by yhuard** [comment]
Hi @emanuelaepure,

As far as I know, this is not foreseen in a near future. If you want to implement this feature on your side, you're free to do so.

For feature requests, please contact [COMM Europa Management](mailto:Europamanagement@ec.europa.eu). You might get a better answer there.

Have a nice day!
