### ISSUE TITLE
ECL v1 - Overlapping between expanded navigation menu item and Inpage navigation

### ISSUE THREAD

**Issue by alessandro-russo** [ec-europa/europa-component-library#1350]
### ECL version
v1.x (latest: 1.12.1)

### Expected behavior
**Settings:** navigation menu and inpage navigation on same page.

When a navigation menu item is expanded, it *must not* "overlap with" the inpage navigation items.

### Actual behavior

When a navigation menu item is expanded, it "overlaps with" the inpage navigation items (see image).

The expanded menu item has `z-index: 1`, while the inpage navigation is wrapped by a `div` with class `ecl-u-z-navigation` (i.e., `z-index: 10`).

<img width="1440" alt="demo-issue" src="https://user-images.githubusercontent.com/26624967/66932547-16a11100-f038-11e9-9e60-59b482fa1482.png">

### Steps to reproduce the issue

Put navigation menu and inpage navigation on same page; see attached zip where the "Page with menu" demo is combined with the "Inpage navigations" demo (where the dark grey "Example row" is removed to emphasize the issue).

[demo_issue.zip](https://github.com/ec-europa/europa-component-library/files/3735099/demo_issue.zip)

---

Thanks!!!

**Comment by yhuard** [comment]
Hi @alessandro-russo ,

We'll look into it. 

Thank you for reporting this issue!

**Comment by yhuard** [comment]
Hi @alessandro-russo 

We've just published [ECL v1.13.0](https://github.com/ec-europa/europa-component-library/releases/tag/v1.13.0). Can you confirm that your issue is now fixed? 

Thank you!

**Comment by alessandro-russo** [comment]
Hi @yhuard,

I can confirm that the issue is now fixed in v.1.13.0.

Many thanks for the quick update! :+1:

---

As a side note, I just noticed that as a consequence of #1319 `ecl-icon--facebook` and `ecl-icon--gear` now both correspond to the facebook icon (you can see it in the [icons demo page](https://ec-europa.github.io/europa-component-library/ec/components/preview/ec-style-icon))...but I should probably report this in a separate issue.
