### ISSUE TITLE
ECL v1.13.0 - Conflict between 'facebook' and 'gear' icons

### ISSUE THREAD

**Issue by alessandro-russo** [ec-europa/europa-component-library#1357]
### ECL version
v1.13.0

### Actual behavior
As a consequence of #1319, `ecl-icon--facebook` and `ecl-icon--gear` both correspond to the facebook icon

### Steps to reproduce the issue
See `ecl-icon--facebook` and `ecl-icon--gear` in the [icons demo page](https://ec-europa.github.io/europa-component-library/ec/components/preview/ec-style-icon)

---

Thanks for your support!!!

**Comment by emeryro** [comment]
Thanks for the feedback.
I can indeed reproduce the bug. We will fix it shortly

**Comment by yhuard** [comment]
Hi!

The quick fix provided by @emeryro has been published in [ECL 1.13.1](https://github.com/ec-europa/europa-component-library/releases/tag/v1.13.1).

Thank you @alessandro-russo for reporting this issue!

**Comment by alessandro-russo** [comment]
Many thanks for the quick fix and update! :+1:
