### ISSUE TITLE
[V1] HTML attributes' values are not escaped

### ISSUE THREAD

**Issue by LOBsTerr** [ec-europa/europa-component-library#1369]
PR - https://github.com/ec-europa/europa-component-library/pull/1368

### Expected behavior
All values of attributes should be escaped

### Actual behavior
Attributes' values are not escaped

### Steps to reproduce the issue
Drupal uses special attributes to handle js on the forms. As a result some of attributes can contain json, which should be escaped in order to be handled correctly

For example:
```
{"disabled":{":input[name='override_permissions'":{"value":1}}}
```

**Comment by kalinchernev** [comment]
Suggestion has been merged and published in [1.15](https://github.com/ec-europa/europa-component-library/releases/tag/v1.15.0).
