### ISSUE TITLE
Harmonised template menu example incomplete

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1408]
### Expected behavior
I am trying to adapt our IS to use ECL v2 by adapting our menu with the armonised site header, see link:
https://ec.europa.eu/component-library/ec/harmonised-templates/site-header/group1/

### Actual behavior
When going to playroom and clicking on any of the items of the menu I won't see the children items, but will get redirected,  see: https://ec.europa.eu/component-library/playground/ec/?path=/story/components-site-headers-harmonised--group-1

I have seen that menu component is about to disappear: https://ec.europa.eu/component-library/playground/ec/?path=/story/components-navigation-menu-legacy--default
and tried using Expandable component but saw that it neither serves the purpose of the menu nor has the same structure, so my question is:

How can I make menu expandable items work for my harmonised site header?
Thanks

**Comment by yhuard** [comment]
Hello @dhamaris,

The navigation system of ECL 2, including the megamenu, is not ready yet. As far as I know, UX and Usability teams are still working on it. After that, the Design team will provide us specifications that we, developers, can follow to implement the component.

I can't give you an estimate as to when it will be ready, and unfortunately https://ec.europa.eu/component-library/playground/ec/?path=/story/components-navigation-menu-legacy--default is not compatible with the new site headers.

I'm really sorry for the inconvenience. Maybe [COMM Europa Management](mailto:Europamanagement@ec.europa.eu) can give you a more details answer.

**Comment by pitommasi** [comment]
What should we use in the meantime?

**Comment by Yaomimi** [comment]
Could you tell us when you need this component? It is our top priority to create it.

**Comment by pitommasi** [comment]
ASAP, I am preparing some screenshots...

**Comment by pitommasi** [comment]
is the menu in [this page](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Menu+-+Design+Specifications) the correct one to be used in the Harmonised - group 1 website?
Can I adapt those screenshots for my mock-up?

**Comment by Yaomimi** [comment]
Hi, sorry for the delay. This ticket contains the menu specifications. Menu will be released this week. Referencing https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Menu+-+Design+Specifications

**Comment by pitommasi** [comment]
that's great news, thanks. 

Will it also be available in the playground by this week?
