### ISSUE TITLE
ECL V1 Catalogue no longer accesible

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1458]
Until yesterday, this link was accessible: https://ec-europa.github.io/europa-component-library/ec/components/detail/ec-component-listing

Now this page is no longer working. We need documentation about ECL v1 in order to maintain our web applications that are using it.

**Comment by kalinchernev** [comment]
@dhamaris ECL v1 documentation is no longer hosted on github pages.
Please use the following information for accessing previous versions' documentation: https://github.com/ec-europa/europa-component-library#previous-major-versions
