### ISSUE TITLE
IE Site Header issues

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1459]
Hi, header on the last version is showing black dots for Site Header Harmonised Group 1, for IE:

![image](https://user-images.githubusercontent.com/1392485/71077679-277d1880-2188-11ea-9a95-2bd941bd74c8.png)

**Comment by emeryro** [comment]
Hi, sorry for the delay.
This issue has been fixed on our dev; the fix will be part of the next release

**Comment by kalinchernev** [comment]
Fixed in https://github.com/ec-europa/europa-component-library/releases/tag/v2.22.0
