### ISSUE TITLE
Please help on svg stuff

### ISSUE THREAD

**Issue by edtruant** [ec-europa/europa-component-library#1524]
Don't know exactly if this is an issue, or me not able to understand the svg stuff...
We're experiencing some problems when it comes to refer to your .svg icons from within the markup, maybe cause we're rookies with .svgs.

We've copied the whole dist folder within our project and tried to adjust the html markup links to refer the proper svgs... but still we don't know where to find, for instance, the icon called "icons.865a18d2.svg#ui--corner-arrow".

Here is the markup form the ECL playgroud at https://ec.europa.eu/component-library/playground/ec/?path=/story/components-site-headers-harmonised--group-1

`<a href="/example" class="ecl-menu__link" data-ecl-menu-link="true">Item 2
    <svg focusable="false" aria-hidden="true" class="ecl-menu__link-icon ecl-icon ecl-icon--xs ecl-icon--rotate-180">
        <use xlink:href="dist/images/icons.865a18d2.svg#ui--corner-arrow">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ui--corner-arrow">
                           <path d="M20.623 19.5L12 9.83 3.377 19.5 1 16.835 12 4.5l11 12.335z"></path>
                </svg>
        </use>
    </svg>
</a>`

There is no icon called icons.865a18d2.svg in the dist folder, could you please explain how to refer sgvs properly.

Many thanks for helping

**Comment by edtruant** [comment]
Forgot to say, I work in this project...

https://easin.jrc.ec.europa.eu 

Thanks.
Fabio D'Amico.

**Comment by kalinchernev** [comment]
@edtruant please have a look at the getting started guide here https://ec.europa.eu/component-library/ec/getting-started/

Once you have ensured that the CSS and the actual SVG resources are correctly linked to your documents, you can use

```
<svg focusable="false" aria-hidden="true" class="ecl-icon ecl-icon--s"><use xlink:href="path/to/images/icons.svg#general--hamburger"></use></svg>
```

There's no need to specify 865a18d2, it's a sample hash from ECL's demo building process which you don't need to take.

**Comment by dhamaris** [comment]
I understand your confusion @edtruant , the components catalog contains paths that don't exist in the actual package and some of us have lost time at the beginning trying to figure out why the paths to the svgs are different.

@kalinchernev maybe a reminder saying that image paths are not to be used would be useful: https://ec.europa.eu/component-library/ec/guidelines/images/
Also indicating where the real ones are, something like: 
dist/images/icons.865a18d2.svg -> <path_to_your_theme>/assets/images/icons/sprites/icons.svg

Thank you

**Comment by kalinchernev** [comment]
Guidelines added https://ec.europa.eu/component-library/ec/guidelines/images/
