### ISSUE TITLE
Missing language selector breaks javascript close button functionality.

### ISSUE THREAD

**Issue by ghost** [ec-europa/europa-component-library#1530]
### Expected behavior

I am able to close messages on the website with their "Close this message" button, regardles of whether the language selector is present on the page.

### Actual behavior

When you do not have the language selector present on the page. You can not close messages with their close button. The following error message appears in the console:

```
drupal.js?v=8.8.1:13 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at l.e.init (ecl-ec-preset-legacy-website.js?q54l8r:2)
    at Function.l.autoInit (ecl-ec-preset-legacy-website.js?q54l8r:2)
    at ecl-ec-preset-legacy-website.js?q54l8r:2
    at Array.forEach (<anonymous>)
    at Object.e.autoInit (ecl-ec-preset-legacy-website.js?q54l8r:2)
    at Object.attach (ecl_auto_init.js?q54l8r:8)
    at drupal.js?v=8.8.1:25
    at Array.forEach (<anonymous>)
    at Object.Drupal.attachBehaviors (drupal.js?v=8.8.1:22)
    at drupal.init.js?v=8.8.1:28
```

### Steps to reproduce the issue

- Install a site without the language selector element on the page
- Visit a page where a message is generated
- Try to close the message box

I know that the language selector element is mandatory on the header as described here:
https://ec.europa.eu/component-library/ec/core-template/site-header/usage/

Yet that is no reason not to check for it if it is present in the javascript before trying to add an eventlistener to the element. These look to be the lines in question: https://github.com/ec-europa/europa-component-library/blob/d7bf128e8101e57ae19cf9c1cc1f2dd2cdb87ec1/src/systems/ec/implementations/vanilla/packages/ec-component-site-header/ec-component-site-header.js#L57-L58

If there is official documentation on what to do when you only have one language on your site I would like to see it. As the link in this issue https://github.com/ec-europa/europa-component-library/issues/690 is not functioning any longer.

**Comment by kalinchernev** [comment]
Solved in https://github.com/ec-europa/europa-component-library/pull/1531

**Comment by kalinchernev** [comment]
Released in https://github.com/ec-europa/europa-component-library/releases/tag/v2.23.0
@verbruggenalex thanks for reporting the issue

**Comment by ghost** [comment]
Thanks @kalinchernev
