### ISSUE TITLE
Text within body tags should receive the same font-family and font-size

### ISSUE THREAD

**Issue by ghost** [ec-europa/europa-component-library#1533]
### Expected behavior

When accidentally forgetting to use `<p>` tags or when not using `<p>` tags on purpose you should still receive the same font-family and font-size on the text.

### Actual behavior

Right now for me the only formatting on text outside of a paragraph is the line-height. The font-family differs from text within paragraphs.

### Steps to reproduce the issue

Visit any of these drupal core pages: https://github.com/drupal/drupal/blob/646584b3f718897179589f4f014531e3d9365331/core/modules/system/src/Controller/Http4xxController.php#L10

**Comment by Joosthe** [comment]
ECL does not alter the body tag, as it is outside a component. So indeed, there is no css added here, but this can be add this in your theme.

**Comment by ghost** [comment]
That's what we did for our project yes. I just thought I would let you guys know as it seems kind of unnatural that ECL is forcing fonts on other elements like h1 with the `!important` rule: https://github.com/ec-europa/europa-component-library/blob/7f867ec68a8fb04fa65594ef9a42b422d87d1c00/src/systems/ec/implementations/vanilla/packages/ec-utility-typography/ec-utility-typography.scss#L12-L14

So a project can be compliant with Europa's web guidelines when they use another font for elements that are not covered by ECL?

When reading https://wikis.ec.europa.eu/display/WEBGUIDE/01.+Web+design+principles

It states:
> Design effectively: Be respectful of a user's time. Design predictable, reusable solutions to solve similar problems. Streamline and optimise the experience. Anticipate needs to help people work better, smarter and faster. Standardised, reusable solutions also contribute to the cost-effectiveness of the European Commission's communication effort.    

In my opinion, regardless of having two font types in one website is compliant or not, I think that the most effective thing to do is to have ECL set the font on the body tags. This to avoid developers having to report this unnatural behavior.

If it is absolutely a no-go to set the font on the body tags I recommend that you update the documentation on typography that only elements covered by ECL are styled:
https://ec.europa.eu/component-library/ec/guidelines/typography/

**Comment by kalinchernev** [comment]
Hi @verbruggenalex thanks for flagging this topic!

There was an attempt from my side to add explanations on typography and styling of content and components in this pull request https://github.com/ec-europa/europa-component-library/pull/1548

However, there's no person in ability to approve this information going public on the website of ECL, so it ended up on this internal page together with few more FAQs: https://webgate.ec.europa.eu/CITnet/confluence/display/FRONT/Frequently+asked+questions

One of the main goals of ECL is to be incrementally adoptable and non-intrusive. The reason there are no "global" styles applied. Holds true for the `body` but also `p` and others. It was particularly important for ECL to have this approach of providing styles only when users add `.ecl-` rule during the "transformation" of sites having existing CSS for portions of the website and still having the header, footer, etc.

The way ECL handles text styling is done in 2 approaches mainly:
- through the typography utilities you have mentioned
- by the `.ecl-editor` class which is the recommended approach for having content styled `.ecl-` classes

The typography utility is for 2 main use cases: styling text in components and styling text generated by templates. (like twig in Drupal for instance). These are cases where the implementer has control over the text.

The ECL editor is for CMS which has WYSIWYG editors allowing for non-developers to manage content. In this case the implementer does not have control over the text and thus `p` should be styled accordingly. ([these are the rules](https://github.com/ec-europa/europa-component-library/blob/v2-dev/src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--typography.scss))

I hope these could clarify a bit the reasoning and the approach behind not setting global rules in favor of providing 2 means for users to implement styles intentionally.
