### ISSUE TITLE
Table header have no ecl styling

### ISSUE THREAD

**Issue by zarabatana** [ec-europa/europa-component-library#1545]
### Expected behavior
Applying css classes to table I get ecl styling.

### Actual behavior
It's missing css style for table header.

### Steps to reproduce the issue
Creating a table using ecl classes:
https://ec.europa.eu/component-library/ec/components/table/code/

**Comment by Joosthe** [comment]
Could you specify more what styling you are talking about. Because when i check the steps to reproduce this i do get styling on the table-header .

**Comment by kalinchernev** [comment]
Internal ticket for reference https://webgate.ec.europa.eu/CITnet/jira/browse/FRONT-977
@zarabatana please provide more details for the issue if you still have it.

**Comment by emeryro** [comment]
cannot reproduce and no other information, closing this issue
