### ISSUE TITLE
ECL v2 does not have navigation lists component

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1552]
Hi, version 2 of the ECL does not contain this component any longer, as v1 did:
https://ec.europa.eu/component-library/v1.15.0/ec/components/detail/ec-component-navigation-list/

The most similar component is https://ec.europa.eu/component-library/ec/components/navigation/menu/code/

Is there any component that fits the older one better? Are you planning on adding it?

**Comment by dhamaris** [comment]
I guess the answer is no, there won't be navigation lists for ECL V2, and the most similar component would be inpage navigation. Please correct me if I am wrong. Thank you.

**Comment by kalinchernev** [comment]
Hi @dhamaris FRONT-978 was created internally to follow-up on the question.
For the moment there are no plans for migration of the navigation lists component. 
The menu component has been under continuous evolution and will look and behave very differently from the navigation lists.
In terms of what the component aims to achieve, the closest implementation you can use is the accordion https://ec.europa.eu/component-library/ec/components/accordion/usage/
