### ISSUE TITLE
Webpack4 example not working

### ISSUE THREAD

**Issue by Loz83** [ec-europa/europa-component-library#1555]
Hello,
I'm trying to use europa-component-library with webpack4 inside an Asp.Net core 3.1 solution, and was looking to run the webpack 4 example (https://github.com/ec-europa/europa-component-library/tree/v2-dev/examples/webpack4) but it does not work.
Tried with both yarn and npm results in the same problem and warning:

_Module not found: Error: Can't resolve './locale' in '[root]\node_modules\@ecl\ec-preset-website\dist\scripts'_

Simply follow the example description to reproduce.

I'm having the same warning in my Asp.Net Core solution and no global ECL variable is defined globally in the pages

Best
Lorenzo

**Comment by kalinchernev** [comment]
@Loz83 any chance you could try the latest version as suggested in #1566?

**Comment by kalinchernev** [comment]
PR merged, re-open with steps to reproduce if still relevant.
