### ISSUE TITLE
SVGs get removed by Drupal

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1561]
Hi, we are working in Drupal 8.8.2 and currently tags like SVG get filtered when rewriting a field from a view. It is due to a class called XSS.php, which prevents XSS by filtering certain tags, one of them svg. It is related to this issue: https://www.drupal.org/project/drupal/issues/2840938

This problem did not occur with ECL v1 because images were accessed from CSS, now the v2 uses svg and use which is cool but is giving us headaches. Anyone has faced this problem yet? Does any Drupal expert have any recommendation?

If we don't find a solution on the Drupal side we were thinking about exchanging svgs by other images as pngs or jpgs. Would that be possible or is the markup for footer, header, files, and so on fixed?
Thanks a lot

**Comment by kalinchernev** [comment]
@dhamaris the issue has been followed-up internally at FRONT-979
We haven't faced such issues before. It's clear that the CMS is the issue which prevents you from using SVGs. 
SVGs in ECL v2 were very carefully selected as a delivery resources compared to font icons. There were many more issues with font icons and they were not as flexible.
Have you tried to report the issue at a platform level?

**Comment by dhamaris** [comment]
I haven't yet, for the moment i tackled the problem avoiding using rewrite for views in Drupal, thanks for looking into it. You can close this ticket.

**Comment by kalinchernev** [comment]
Thanks for the follow-up!
