### ISSUE TITLE
ECL v2 Menu: Maximum number of element in the same column

### ISSUE THREAD

**Issue by SergioSVQ** [ec-europa/europa-component-library#1575]
Hi, 

In the ECL v2, Menu items with children have a maximum of four items in the same column. The fifth item is shown in another column. This is because the CSS property of the grid-template-rows is set to four(auto auto auto auto). My question is whether it is possible to set by some parameter the number of elements in the same column or otherwise it should not be changed at all.

Thank you in advance,

**Comment by kalinchernev** [comment]
Ticket created for a follow-up https://webgate.ec.europa.eu/CITnet/jira/browse/FRONT-1057

**Comment by emeryro** [comment]
Hello, sorry for the delay.
It is not possible to change the number of item per column in the menu, as it is part of the specification and guidelines of the menu.
If there are identified needs, it may be evaluated, but for now the limit to 4 items is fixed
