### ISSUE TITLE
ecl-typography class not available in ECL v2

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1577]
I am looking for a class that only affects font-family, so that i can add it to the body and make sure text has the same format. It seems that in the new releases of ECL it is no longer available, it used to be this:

.ecl-typography {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizelegibility; 
}

Looking at the [catalog](https://ec.europa.eu/component-library/ec/utilities/typography/code/) all classes also add size. Why did you remove ecl-typography? Can you provide us with a similar class? I can add it myself in a custom css but I don't think it is good long term idea.

Thanks

**Comment by kalinchernev** [comment]
https://webgate.ec.europa.eu/CITnet/jira/browse/FRONT-1059 created for a follow-up.

**Comment by kalinchernev** [comment]
@dhamaris I just had a look at the issue here in more detials
The typography-related classes are under utilities, and namespace is `ecl-u-type-` and not `ecl-typography`, it's been as such for long time, not latest release. Please double-check samples you've mentioned.

As a related topic please see https://github.com/ec-europa/europa-component-library/issues/1533#issuecomment-615239327
It's not recommended to apply typography styling on the body, aim to either apply such through templates or corporate Drupal theme for components or use the `.ecl-editor` for content.

**Comment by dhamaris** [comment]
Thank you for your explanation, I don't find ecl-editor class in the css from ECL 2.26, is it meant to be there?

**Comment by kalinchernev** [comment]
It's not demonstrated, but available as a preset: https://www.npmjs.com/package/@ecl/ec-preset-editor/v/2.26.0 (or https://registry.npmjs.org/@ecl/ec-preset-editor/-/ec-preset-editor-2.26.0.tgz) the contents being https://github.com/ec-europa/europa-component-library/tree/c0673e170660d23d324546edc57388f0f86c6ac0/src/systems/ec/implementations/vanilla/packages/ec-preset-editor

**Comment by dhamaris** [comment]
We have always used ec-preset-website package as it seemed it had everything we needed (and paradoxically the *-full package had less styles than *-website).

How can i get the css for ecl-editor and still use ec-preset-website? We are not using npm for our website, we are just getting the packages and putting them where they belong.

![image](https://user-images.githubusercontent.com/1392485/79966974-82a07e00-848e-11ea-8ec7-f0039f4e6509.png)

Thank you

**Comment by kalinchernev** [comment]
As I mentioned, the styles are available here https://registry.npmjs.org/@ecl/ec-preset-editor/-/ec-preset-editor-2.26.0.tgz
You can download the source in the same way as you do for the other presets. You can add this CSS of `package/dist/styles/ecl-ec-preset-editor.css` in addition to the website preset you are already using.

Edit: the links in releases for website presets are highlighted links based on business decisions. Not meaning you can't use the other ECL assets which are not so "advertised".

**Comment by dhamaris** [comment]
Hello, I reopen this ticket because I am now migrating to the ECL V3 and I would love to have something like the ecl-editor class, Do you have something similar to apply styles to a section? I ask this because some of our sites have WYSIWYG managed by users that don't know about programming, and it would help apply styles to unorganized contents such as this.
