### ISSUE TITLE
JS from ECL v2 throws errors in IE 11

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1578]
### Expected behavior
JS loads with no errors in IE 11.
### Actual behavior
ECL is not initialised due to js errors
### Steps to reproduce the issue
Open Internet Explorer 11 and go to [https://ec.europa.eu/component-library/playground/ec/?path=/story/components-site-headers-harmonised--group-1](https://ec.europa.eu/component-library/playground/ec/?path=/story/components-site-headers-harmonised--group-1)
Open console and type: ECL 
ECL object should be initialised, but JS errors prevented it, so ECL behaviour won't be applied.

![image](https://user-images.githubusercontent.com/1392485/79227169-c9272480-7e5f-11ea-92f2-f339fea60e5d.png)

**Comment by kalinchernev** [comment]
https://webgate.ec.europa.eu/CITnet/jira/browse/FRONT-1060 created for a follow-up.

**Comment by kalinchernev** [comment]
I tried to reproduce but couldn't.

This is the result I get using the provided link

![iframe-manager](https://user-images.githubusercontent.com/1923476/79740414-ecd6e880-82ff-11ea-9560-20ab51d41508.png)

That's what I get in the full screen version:

![iframe-fullscreen](https://user-images.githubusercontent.com/1923476/79740441-f52f2380-82ff-11ea-8878-41cb587a10f2.png)

In neither case there are JS errors at the moment. It could be that was a network issue on a certain load that the JS scripts haven't been loaded and thus the issue.

**Comment by dhamaris** [comment]
There must been some problem with our network that causes problems with the loading of external assets, i downloaded ecl js and css and referenced them locally instead of using your external repository and it works now. 

The reason why I could not see your ECL catalog was that my IE11 was configured with settings form IE7 by default.
