### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by pitommasi** [ec-europa/europa-component-library#1592]
Apologies in advance if it's not the right way to ask this but since there is no search engine on the [ECL page](https://ec.europa.eu/component-library/ec/), I'll ask here.

Is there any tooltip component in the ECL for EC harmonised website?

Thanks in advance

Bests,

Pierpaolo

**Comment by emeryro** [comment]
Hello,
Indeed, there are no tooltip component available in ECL.
For simple use cases, the default html element `title` may be enough; if not, that would require a custom implementation

Best regards,
Romain

**Comment by pitommasi** [comment]
Thank you for the information.

Bests,

Pierpaolo
