### ISSUE TITLE
ECL Flag icons for countries

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1595]
Are there official icons for European flags?

I've seen all these examples but some don't use flags, others show flags but they are not suitable for us (they have different sizes or strange 3D effect)

[https://cohesiondata.ec.europa.eu/countries](https://cohesiondata.ec.europa.eu/countries
)

[https://ec.europa.eu/info/business-economy-euro/euro-area/what-euro-area_en
](https://ec.europa.eu/info/business-economy-euro/euro-area/what-euro-area_en
)
[https://ec.europa.eu/easme/en/section/life/life-eu-countries#inline-nav-4
](https://ec.europa.eu/easme/en/section/life/life-eu-countries#inline-nav-4
)
[https://ec.europa.eu/research/horizon2020/index.cfm?pg=country-profiles
](https://ec.europa.eu/research/horizon2020/index.cfm?pg=country-profiles
)
[https://ec.europa.eu/education/study-in-europe/country-profiles_en
](https://ec.europa.eu/education/study-in-europe/country-profiles_en
)
Do you know of any example, or can provide us with one, that uses plain and uniform icons for flags?

**Comment by emeryro** [comment]
Hello,
What I can tell you is that ECL does not provide any flag icons.
Now, to get a better answer to your question I suggest you to contact COMM Europa Management (the email address is available here https://ec.europa.eu/component-library/ec/). They will probably be able to point you to the official pages for this
