### ISSUE TITLE
Navigation menu active items won't change their color

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1599]
If I click on an element of the menu, see: https://ec.europa.eu/component-library/ec/components/navigation/menu/code/
Active menu links won't be noticed and set as grey, as they do when I hover, like here:

![image](https://user-images.githubusercontent.com/1392485/83767203-a48c4380-a67d-11ea-8b7f-46231d06e127.png)

You can reproduce this by opening this link using chrome:  https://ec.europa.eu/component-library/ec/components/navigation/menu/code/, opening developer tools, and after selecting the link element, clicking on "active" checkbox, see image:

![image](https://user-images.githubusercontent.com/1392485/83767388-e1583a80-a67d-11ea-9635-6753e43ac900.png)

Is it intended to be like that? I remember I was using the class ecl-menu__link--current but I am not sure if it is needed anymore.

**Comment by emeryro** [comment]
Hello,
This behavior is not intended.
We plan to update the way menu reacts to events soon, to make keyboard navigation possible too. So basically it should open on active and focus.
This should solve your issue.

And indeed, class ecl-menu__link--current is no longer needed
