### ISSUE TITLE
JS Error when selecting option in multiselect

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1654]
When I click on an option of multiselect, I get this error in my console:
"forEach is not a function"

![image](https://user-images.githubusercontent.com/1392485/91989354-b8088280-ed30-11ea-81d0-05cc0c2da7b4.png)

I've looked it up and it seems that in the method  handleClickOption when trying to iterate through the options, forEach is not a valid function because those options aren't an Array but a HTMLCollection.
I tried to reproduce it in your catalog but somehow it does not fail.

Thank you

**Comment by kalinchernev** [comment]
@dhamaris given the fact you haven't been able to reproduce on playground, can you share a way to reproduce?
Can please put a debugger on this line and share the values of:
- `this` is it scoped correctly?
- what is `this.select` and does it match the actual select?
- is `this.select.options` actually defined?

Note for maintenance team: I've created FRONT-1576 ticket

**Comment by dhamaris** [comment]
This is the aspect of these variables:

this:
![image](https://user-images.githubusercontent.com/1392485/92244007-a3f48a80-eec2-11ea-9673-ae5009729bda.png)
this.select: (this.select does match the select I am checking, yes)
![image](https://user-images.githubusercontent.com/1392485/92244301-00f04080-eec3-11ea-9442-dd27057c74b7.png)
and options:
![image](https://user-images.githubusercontent.com/1392485/92245139-33e70400-eec4-11ea-92fa-869909315467.png)
but foreach is undefined:
![image](https://user-images.githubusercontent.com/1392485/92245236-5547f000-eec4-11ea-99c2-a102977f53e2.png)

**Comment by dhamaris** [comment]
I forgot to add, if I look at the prototype attribute of HTMLCollection, forEach function is not defined, so as I am using the same browser for both cases,  my guess is that in the catalog somewhere that forEach function is added to the prototype of HTMLCollection.
Here my app:
![image](https://user-images.githubusercontent.com/1392485/92246705-6b56b000-eec6-11ea-930a-65e50ed1a014.png)
Here the catalog:
![image](https://user-images.githubusercontent.com/1392485/92246831-9c36e500-eec6-11ea-9fc6-a993716ac08c.png)

**Comment by dhamaris** [comment]
You can use this snippet putting js and css where they belong:

```
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8" />
    <title>Page title</title>
    <meta content="width=device-width,initial-scale=1" name="viewport" />
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
      var cl = document.querySelector('html').classList;
      cl.remove('no-js');
      cl.add('has-js');
    </script>
    <link
      rel="stylesheet"
      href="css/ecl-ec-preset-website.css"
    />
    
  </head>
  <body>
    <!-- paste the markup from the template here -->
	<script src="js/ecl-ec-preset-website.js"></script>
    <script>
      $(document).ready(function(){
         ECL.autoInit();
      });
     
    </script>
    
    <div class="ecl-form-group"><label class="ecl-form-label" for="select-multiple-1">SELECT MULTIPLE 1<span class="ecl-form-label__required">*</span></label>
  <div class="ecl-help-block">This is the input&#x27;s helper text.</div>
  <div class="ecl-select__container ecl-select__container--m"><select id="select-multiple-1" data-ecl-select-default="Placeholder text" data-ecl-select-search="Search" 
  data-ecl-select-all="Select all" id="select-multiple" class="ecl-select" required="" multiple="" data-ecl-select-multiple="true" data-ecl-auto-init="Select">
      <option value="1">Belgium</option>
      <option value="2">France</option>
      <option value="3">Luxembourg</option>
      <option value="4">Germany</option>
      <option value="5">Bulgaria</option>
      <option value="6">Italy</option>
      <option value="7">Romania</option>
      <option value="8">Greece</option>
      <option value="9">Hungary</option>
      <option value="10">Portugal</option>
    </select>
    <div class="ecl-select__icon"><svg focusable="false" aria-hidden="true" class="ecl-select__icon-shape ecl-icon ecl-icon--s ecl-icon--rotate-180">
        <use xlink:href="dist/images/icons.865a18d2.svg#ui--corner-arrow"></use>
      </svg></div>
  </div>
</div>



    
    
  </body>
</html>
```

**Comment by kalinchernev** [comment]
@dhamaris thanks for the detailed feedback!
Managed to reproduce https://codepen.io/kalinchernev/pen/jOqxERO
I'm on it

**Comment by emeryro** [comment]
issue solved, it will be part of next release

**Comment by dhamaris** [comment]
Perfect, thanks a lot!
