### ISSUE TITLE
Multiselect: checked options lost after filtering

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1655]
### Expected behavior
I am using ECL select to filter results, and everything works fine when I click on the options:

![image](https://user-images.githubusercontent.com/1392485/91968133-79fd6580-ed14-11ea-9aaf-3e87e1550496.png)

### Actual behavior
When I filter to search by this options, the html that is returned seems fine but the selection is lost:

![image](https://user-images.githubusercontent.com/1392485/91968390-e4160a80-ed14-11ea-9f46-6eac6b3ab924.png)

Is this behaviour intended or is there something I am doing wrong? 

Thank you

**Comment by kalinchernev** [comment]
Can you please share details on which browser is used?

**Comment by dhamaris** [comment]
I'm using Chrome browser

**Comment by kalinchernev** [comment]
Which version and which operating system?
I also do not understand the steps to reproduce fully.
Can you be more specific what you're searching? Screenshots look like there is no search query but rather "select all" toggling?

**Comment by dhamaris** [comment]
Sorry, I use Version 84.0.4147.125 (Official Build) (64-bit). I am using Windows XP at the moment.
When I say "Search" I don't mean the autocomplete search from the widget but rather a button that submits my search and reloads the page. Once reloaded, the select tag contains a list of options and the "selected" attribute is present in those options I selected before submitting. Despite this, the checkbox does not appear as selected, as it only occurs with onclick and not when drawing things for the first time.
This is impossible to reproduce in the catalog since the catalog is just static html.

But a way to test would be to make a simple "Hello World" select where 2 out of 3 options are selected, that is <option> element contains "selected" attribute. Something like this:


```
<div class="ecl-form-group"><label class="ecl-form-label" for="select-multiple">Select a country<span class="ecl-form-label__required">*</span></label>
  <div class="ecl-help-block">This is the input&#x27;s helper text.</div>
  <div class="ecl-select__container ecl-select__container--m"><select data-ecl-select-default="Placeholder text" data-ecl-select-search="Search" data-ecl-select-all="Select all" id="select-multiple" class="ecl-select" required="" multiple="" data-ecl-select-multiple="true" data-ecl-auto-init="Select">
      <option selected value="1">Belgium</option>
      <option selected value="2">France</option>
      <option value="3">Luxembourg</option>
    </select>
    <div class="ecl-select__icon"><svg focusable="false" aria-hidden="true" class="ecl-select__icon-shape ecl-icon ecl-icon--s ecl-icon--rotate-180">
        <use xlink:href="dist/images/icons.865a18d2.svg#ui--corner-arrow"></use>
      </svg></div>
  </div>
</div>
```


When you have an html like that, does it appear as selected when it is first loaded?

**Comment by dhamaris** [comment]
You can use this html (putting js and css where they belong). 
See that 1st and 2nd option are selected already, one using "selected" and the other "selected='selected'" and none make the selection effective.

```
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8" />
    <title>Page title</title>
    <meta content="width=device-width,initial-scale=1" name="viewport" />
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
      var cl = document.querySelector('html').classList;
      cl.remove('no-js');
      cl.add('has-js');
    </script>
    <link
      rel="stylesheet"
      href="css/ecl-ec-preset-website.css"
    />
    
  </head>
  <body>
    <!-- paste the markup from the template here -->
	<script src="js/ecl-ec-preset-website.js"></script>
    <script>
      $(document).ready(function(){
         ECL.autoInit();
      });
     
    </script>
    
    <div class="ecl-form-group"><label class="ecl-form-label" for="select-multiple-1">SELECT MULTIPLE 1<span class="ecl-form-label__required">*</span></label>
  <div class="ecl-help-block">This is the input&#x27;s helper text.</div>
  <div class="ecl-select__container ecl-select__container--m"><select id="select-multiple-1" data-ecl-select-default="Placeholder text" data-ecl-select-search="Search" 
  data-ecl-select-all="Select all" id="select-multiple" class="ecl-select" required="" multiple="" data-ecl-select-multiple="true" data-ecl-auto-init="Select">
      <option selected="selected" value="1">Belgium</option>
      <option selected value="2">France</option>
      <option value="3">Luxembourg</option>
      <option value="4">Germany</option>
      <option value="5">Bulgaria</option>
      <option value="6">Italy</option>
      <option value="7">Romania</option>
      <option value="8">Greece</option>
      <option value="9">Hungary</option>
      <option value="10">Portugal</option>
    </select>
    <div class="ecl-select__icon"><svg focusable="false" aria-hidden="true" class="ecl-select__icon-shape ecl-icon ecl-icon--s ecl-icon--rotate-180">
        <use xlink:href="dist/images/icons.865a18d2.svg#ui--corner-arrow"></use>
      </svg></div>
  </div>
</div>

  </body>
</html>
```

**Comment by dhamaris** [comment]
Were you able to reproduce the issue? Please let me know if you need anything else.

**Comment by kalinchernev** [comment]
@dhamaris I personally haven't had the opportunity to spent time on this issue because of management priorities

**Comment by dhamaris** [comment]
Ok, no problem @kalinchernev I just didn't want this issue to go stale because of inactivity.

**Comment by dhamaris** [comment]
After updating the version 33.1 I cannot reproduce the problem anymore, thank you! I close this issue.
