### ISSUE TITLE
Select Dropdown overlapped by footer

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1656]
When the screen height is shorter and my select dropdown reaches my footer, it seems that the footer has more z-index than the selects and appear on top

![image](https://user-images.githubusercontent.com/1392485/91988059-1f253780-ed2f-11ea-8bad-c1c9780bed21.png)

Thank you

**Comment by kalinchernev** [comment]
FRONT-1578 for internal follow up
