### ISSUE TITLE
Many file components in a page

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1682]
Hi, I am migrating a portal that has pages with many links to download different reports, see [here](https://www.euromod.ac.uk/using-euromod/country-reports/f3-onwards).
Even if I add in-page component to group files per version, 28 files using the current ECL takes up a lot of space.
Is there any option for cases like this? Like an accordion or a dropdown? Or are you planning to add a size to file component, so that it can use 30% width in cases like this? I cannot use the dropdown for "Other languages", because it does not serve the purpose (each file is a sibling, not a child)

![image](https://user-images.githubusercontent.com/1392485/94005790-14dee200-fd9f-11ea-902c-c959f158ec61.png)

**Comment by emeryro** [comment]
Hello, sorry for the delay.
As far as I know there are no plan to have a "lighter" version of the file component, but I can raise the point.
For now, you can always use a list of links as it is now, or put files in 2 columns

**Comment by dhamaris** [comment]
Thank you for your answer. Unfortunately I was not allowed to have more than 1 file per row by the IPG Rules team, in the end I added more navigation to split the files into several child pages.
As a suggestion, the same idea of the toggle section that you use when a file has more than 1 language would be useful for a big amount of different files (so the same thing but not hierarchical, something more like a "view more").
I close this ticket.
