### ISSUE TITLE
Inquiry about the ECL language list

### ISSUE THREAD

**Issue by SergioSVQ** [ec-europa/europa-component-library#1714]
The need has arisen to translate a drupal portal into two languages, English as usual and Spanish. Therefore, we were reviewing and saw the language list component (https://ec.europa.eu/component-library/ec/components/language-list/code/). The fact is to perform a new page language list (prior to access the application) and having only two languages is a little bit strange actually. 
The outcome would be the following:

![image](https://user-images.githubusercontent.com/36952941/96441535-f3d8a800-1209-11eb-9e47-0cd683e613f1.png)

Keep in mind the picture above:  Would the language list component be mandatory to use despite having only two languages? Would there be another possibility to put a language switcher always visible on any pages in the application?

We actually appreciate your support.
Best

**Comment by emeryro** [comment]
Hello, 
The language select page is indeed marked as mandatory when there are more than one language available. The language selector is also part of the site header, and so is available on every page.
Now, the design may be challenged if there are only a few items, as in your case. But in any case, this component has to be used
