### ISSUE TITLE
Inquiry about modal dialog

### ISSUE THREAD

**Issue by botisg** [ec-europa/europa-component-library#1731]
Greetings,

as I can see the dialog component no longer exists at version 2. 
As I'm currently using ECL to redesign a website heavily based on dialogs I would like to ask if you have any recommendations on how to replace the existing dialogs with other ecl compliant components.

Thank you

**Comment by kalinchernev** [comment]
The gallery and the language list have overlays (previous dialog) but they are no longer abstracted in a reusable way.

**Comment by botisg** [comment]
Thank you for your reply. The dialogs are currently used in forms, allowing the user to add new options without leaving the original form page. 
What would you propose in this case? Should I use overlay functionality from gallery, use thrid party modal plugin or drop the dialog design completely?

**Comment by kalinchernev** [comment]
In general, dialog interface for such purpose might not be the most convenient, so if there is an option to leave it out, it'll make the form easier to navigate for sure. Using a plugin for it is an option of course too.

I think the gallery component is doing too much for this case. ([code](https://github.com/ec-europa/europa-component-library/blob/dcb35b760bb708d8403270c6b5f926e557b999cf/src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js)) as it accommodates navigation in the modal.

**Comment by botisg** [comment]
Ok, thank you for the info and suggestions. I'll try to use a plugin or replace the dialogs with expandables.

**Comment by kalinchernev** [comment]
Sure, the [expandables](https://ec.europa.eu/component-library/ec/components/expandable/usage/) are an option
