### ISSUE TITLE
Question about Search Page

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1742]
Hi, I am adapting a Liferay search page (see [here](https://s3platform.jrc.ec.europa.eu/search?p_p_id=3&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_3_struts_action=%2Fsearch%2Fsearch&_3_redirect=%2Fhome&_3_groupId=0&_3_keywords=test)) to be compliant with the ECL, but the problem is that filtering content does not work as in your catalog. In your catalog ([here](https://ec.europa.eu/component-library/playground/ec/?path=/story/templates-pages--search)) the action of filtering occurs once the user clicks on button "Filter results". In our Liferay page the filtering occurs when users click on different options.

I was trying to replace every category with a multiselect but realised that I have to do major changes, so my question is if there is a possibility to use the accordion component instead of a multiselect as it behaves more in line with the behaviour we have in Liferay. So it would look like the last item:

![image](https://user-images.githubusercontent.com/1392485/98389596-8f647800-2054-11eb-8ccd-597fec03b4f5.png)

Thank you

**Comment by emeryro** [comment]
Hi, to me it is fine to use the accordions that way, but I'll double check with the designers to be sure.
I'll come back to you shortly

**Comment by dhamaris** [comment]
Thank you @emeryro, yes let me know what your team says

**Comment by emeryro** [comment]
Hello @dhamaris ,
So I asked the designers about it, and the answer they propose is to use expandables component instead of accordion
