### ISSUE TITLE
How to use the dropdown button component

### ISSUE THREAD

**Issue by serromvil** [ec-europa/europa-component-library#1821]
Hi,

I want to use the dropdown button as in [this page](https://ec.europa.eu/component-library/playground/ec/?path=/story/components-dropdown-legacy--default), but apparently it is not supported by ECL v2. The button is displayed but the options are not deployed. The following error can be seen in the browser console: (ecl-auto-init) Could not find 'DropdownLegacy'.

Could you please advise how to do it properly or an alternative way of displaying a dropdown button?

Thank you,
Sergio

**Comment by adrianodias8** [comment]
I have exact same issue reported here (ecl-auto-init) Could not find 'DropdownLegacy' 
does anyone  know a fix? am I missing something?
