### ISSUE TITLE
Deprecated ECL version no longer available

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2068]
Hi, when I access to the websites indicated here: https://github.com/ec-europa/europa-component-library#previous-major-versions
the website, its links to the catalog are broken (website)

![image](https://user-images.githubusercontent.com/1392485/118500747-5a825d80-b728-11eb-9f45-7740cfb6236b.png)

Can you please help me with this? I am currently using the ECL v1 for one of our projects and I need to access its catalog.
Thank you

**Comment by planctus** [comment]
It seems the link to the v1 website (i guess it's what you meant when you said you needed to access the "catalog"), is working for me, can you check again?

**Comment by dhamaris** [comment]
Hi, I checked 3 days ago and it was working, but now I come back and it is down again: 
https://ec.europa.eu/component-library/v1.15.0/
Can you check?

**Comment by dhamaris** [comment]
Ok, I cannot access from inside my VM, somehow, but from outside it is ok.
Thank you!
