### ISSUE TITLE
Eventhandler added to multiselect won't work

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2078]
Hello, we have a multiselect filter where we intend to refresh the view as soon as the user selects something:
![image](https://user-images.githubusercontent.com/1392485/119476232-28878180-bd4e-11eb-8141-b867aad64867.png)

We added an "onchange" listener on the select tag but it will never get fired. The reason we see is that the select is not displayed, but the divs built around the select, and those divs are the ones listening to "onclick":
![image](https://user-images.githubusercontent.com/1392485/119476371-494fd700-bd4e-11eb-96f4-e6c8e982e8d1.png)

So in order to add a listener that works, we would have to add it to the divs once they've been built by the ECL. We would have to put a timeout delay to await for the divs to be available, and then add our custom "onclick" listener.
```
setTimeout(function(){
	
	$("#select-multiple-div").on("click", function(e){
		//logic related to selection
	});
	
},1000);
```
This solution is a bit sloppy, could you please help us with this? Do you have suggestions on how to address this problem?
Thank you

**Comment by planctus** [comment]
Hello @dhamaris , the reason why your listener doesn't work is that the event is only triggered when there is an interaction by the user, here the value of the select is programmatically updated, instead..
We could dispatch the event ourselves, but it might take time before releasing this, although it's a single line of code,
`this.select.dispatchEvent(new window.Event('change', { bubbles: true })); `, basically, in the `updateCurrentValue()` method of the `Select` class.

**Comment by dhamaris** [comment]
Thank you, I tested it and it works, do you think that it could be added in the next release? We can add it to out current ecl-ec-preset-website.js.

**Comment by planctus** [comment]
we are now focused on the releases of ECL v3, that's why i was telling you that it might take time, we created a ticket for this, so yes, it will probably be in the next release, which is not scheduled yet, though. If it's fine for you i think we can close this issue ;)

**Comment by dhamaris** [comment]
Thank you! Ok, we can wait until ECL v3. I close this issue.
