### ISSUE TITLE
Scroll for Multiselect?

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2123]
Hi, we have a really long list of options in some of our multiselect components, so it spreads down over the end of the page.

![image](https://user-images.githubusercontent.com/1392485/122906246-3ed72c00-d352-11eb-9263-4ae6abc27ebb.png)

Is there any solution for this? 
Thank you

**Comment by emeryro** [comment]
Hi, do you have an URL where we can see it live?

**Comment by dhamaris** [comment]
Not yet, but here is a snippet where you can reproduce it.
[index_multi.txt](https://github.com/ec-europa/europa-component-library/files/6716999/index_multi.txt)

Just change the extension to html, I had to switch to txt because html is not allowed.
Thank you

**Comment by emeryro** [comment]
I'm checking with the designers what could be done here.
Here is the corresponding ticket: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/FRONT-2358

**Comment by emeryro** [comment]
In fact, this issue is already solved in the next version of ECL (3.0.0), which will be released very soon
https://v3--europa-component-library.netlify.app/ec/components/forms/select/code/

**Comment by dhamaris** [comment]
That is great news, thank you! Is the v3 already available to use?

**Comment by emeryro** [comment]
npm packages have been released (currently version 3.0-beta.1), and the website is available for preview: https://v3--europa-component-library.netlify.app/
stable version will come in the coming weeks

**Comment by dhamaris** [comment]
Hi, would it be possible to get the commit where this issue was solved? We are trying to solve it in the 2.39 but we don't have time at the moment to migrate to the v3. Is that possible?
