### ISSUE TITLE
Table pushed to the right when inside ecl-container wrapper

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2134]
Hi, I am having trouble with tables that have many columns. They seem not to be fixed within a fixed width. It seems that once I use the ecl-container wrapper the table is pushed to the right, see image: 

![image](https://user-images.githubusercontent.com/1392485/123448203-f2eae800-d5da-11eb-9ccb-71c324a18eb0.png)

Here is a snippet that better explains it:

[index_overflowing_table.txt](https://github.com/ec-europa/europa-component-library/files/6717204/index_overflowing_table.txt)

If I remove the ecl-container class, I get to see the whole table, but I am using the whole width of the page, which is against ECL rules. 

Thank you

**Comment by dhamaris** [comment]
I think that I have to find a way not to have so many columns in the first place. I will close this ticket, thank you!

**Comment by dhamaris** [comment]
I reopen this issue because I don't find any good solution for cases like this but to add an horizontal scroll on the table.
Is that possible? Will v3 already provide it?

**Comment by emeryro** [comment]
Hi, having an horizontal scrolling on tables is not recommended, for accessibility reasons.
Even in v3, there is no additional behavior to handle cases like this.
I guess that your first approach (reducing the number of columns) is the correct one.

Some possibilities I see:

- split the table in two (it seems to be related to different data pools already)
- group some columns to save space, using the multi header table https://ec.europa.eu/component-library/ec/components/table/code/. For instance, grouping all the "google speech commands" columns would save lots of space

**Comment by dhamaris** [comment]
Thank you for the suggestions, in the end we will use a selector to decide which columns the user wants to see.
