### ISSUE TITLE
Preset website ecl v3.0.3

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2208]
I am trying to find this specific preset, with no luck. 
Has the naming of the presets changed? How can I find it? It would be something like this for 3.0.3. I also tried using npm but it seems this version is still not available.

![image](https://user-images.githubusercontent.com/1392485/133768695-65665644-7c61-4101-bc59-f05c0ab36a41.png)

Thank you

**Comment by planctus** [comment]
Well, the preset has been removed, but migrating from v2 to v3 is not just a matter of retrieving the new packages, being a major version it contains many breaking changes, this the link to the document where those changes are listed, in your case it is pointing to the presets that have been removed and replaced by two presets, preset-ec and preset-eu. ;)
https://github.com/ec-europa/europa-component-library/blob/v3-dev/docs/Migrating-v3.md#presets-and-themes

**Comment by planctus** [comment]
So the links to the tarballs in npm for these two new presets, 3.0.3 version are:
https://registry.npmjs.org/@ecl/ec-preset/-/ec-preset-3.0.3.tgz
https://registry.npmjs.org/@ecl/eu-preset/-/eu-preset-3.0.3.tgz

**Comment by dhamaris** [comment]
Thank you for all the information @planctus, unfortunately I cannot access to the links to provided, I get a {"error":"Not found"}
Do you know what might be the problem?

**Comment by dhamaris** [comment]
Btw, we use the css/js locally because we had problems with the order of loading of the js, and we decided to store the js locally.
Until I get to download the link I am using your js located in your server https://cdn1.fpfis.tech.ec.europa.eu/ecl/v3.0.3/ec/scripts/ecl-ec.js
But I get this error:
![image](https://user-images.githubusercontent.com/1392485/133982082-92a7b2f6-19bb-42e5-aa6d-0f3a0b012f05.png)

**Comment by dhamaris** [comment]
Sorry to add more questions but is the v3 actually officially out? I heard from a colleague from H2 that v3 is not yet out.

**Comment by davidsanchezcrespillo** [comment]
> 
> 
> Thank you for all the information @planctus, unfortunately I cannot access to the links to provided, I get a {"error":"Not found"}
> Do you know what might be the problem?

I am getting the same error when trying to access the presets just by clicking from the browser. What would be the right way to get them? Using npm?

Thanks in advance!

**Comment by dhamaris** [comment]
> > Thank you for all the information @planctus, unfortunately I cannot access to the links to provided, I get a {"error":"Not found"}
> > Do you know what might be the problem?
> 
> I am getting the same error when trying to access the presets just by clicking from the browser. What would be the right way to get them? Using npm?
> 
> Thanks in advance!

The links are still not working....can anyone help us with this?

**Comment by davidsanchezcrespillo** [comment]
> The links are still not working....can anyone help us with this?

In case it helps, I finally managed to get the presets using npm (as mentioned in the [README.md](https://github.com/ec-europa/europa-component-library/blob/v3-dev/README.md) file):

```
> npm i @ecl/preset-eu
> npm i @ecl/preset-ec
```

Maybe the mention "download the latest release of the preset of your choice" in the README.md file could be removed if the presets are not going to be there anymore.

**Comment by dhamaris** [comment]
Thanks a lot @davidsanchezcrespillo, that did the trick. 
Is momentjs necessary for the ECL to work? I had to download it https://momentjs.com/downloads/moment.min.js 
so that ecl-ec.js could run with no errors.

**Comment by davidsanchezcrespillo** [comment]
Thanks to you @dhamaris, the moment.js tip was very useful to me (the ecl-eu.js file depends on it too)!
I just found a reference to the moment.js dependence [in the v3 migration notes](https://github.com/ec-europa/europa-component-library/blob/v3-dev/docs/Migrating-v3.md#js-bundle). Maybe it might be included in the "Get started" section too, so that the example is ready to use out of the box?

**Comment by dhamaris** [comment]
Thank you for the link @davidsanchezcrespillo, so by what it says there, It seems that this momentum library is causing problems when building, so it must be separate for now...
I guess I should have read that info more carefully ;)

**Comment by planctus** [comment]
Sorry guys i was out of office in the past week, indeed the links i gave you for the tarballs where wrong, my bad, i've now updated the release page for the [3.0.3 version](https://github.com/ec-europa/europa-component-library/releases/tag/v3.0.3) with the "useful links" as we had them in v2.

- ECL v3 is now the official version of the library, v2 is only in support mode, the packages can be retrieved the way you prefer, but surely the easiest way is from a npm install in an application defining a package.json, as i said this is not mandatory but doing that would surely simplify the process of updating the ECL library on your websites or applications.

- moment.js is indeed an external library not bundled by ECL, so it has to be provided at the application level, it is only used for the datepicker component. Sorry if the  documentation is not always up-to-date or exhaustive, most of that referred to v2 and it has been recently updated for V3, surely we can improve it but if you are about to migrate from v2 please rely on the [document](https://github.com/ec-europa/europa-component-library/blob/v3-dev/docs/Migrating-v3.md) that you have already consulted by yourself.

Sorry if you had to spend time on this, thanks!

**Comment by dhamaris** [comment]
No problem @planctus, thank you for your answers! I close this ticket.
