### ISSUE TITLE
Problem with ECL FileList component

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2212]
Hi, we experienced problems with FileList Component in v2, and it seems it has to do with it not having the forEach method available, we solved it like this but it would be better if it included it newer versions, is that possible?

```
//Fix for ECL2 file upload bug (trying to access forEach of a type that does not define it)
FileList.prototype.forEach = function(cb) { Array.from(this).forEach(cb); };
```
Thank you

**Comment by planctus** [comment]
Mmhh..i think this is confusing, what is this `FileList` you are referring to..? ECL v2 as well as v3 define a **file upload component** for which the library provides a user friendly interface via js in case it is a multiple `<input>`.
FileList is a js object  as returned by the `files` attribute of an input and it doesn't have a `forEach` method but being a "sort of an array" you can use the forEach from `Array.prototype` on it. In Es6 you can do this, for instance: Array.from(input.files).forEach(), so i'm not sure i'm understanding why this would be needed and why would ECL do it on its own.

**Comment by dhamaris** [comment]
I am not sure I follow....I mean this bit:
![image](https://user-images.githubusercontent.com/1392485/135291886-823a269a-e2fc-4e46-9519-6e2e1de39410.png)
If js Files object does not contain forEach method, I would suggest to fix it within the ECL itself,  so that the component can be robust and won't break when using the file upload component, or need an extra tweak.

**Comment by planctus** [comment]
Ohhh, now i see, i was not aware we were actually using a forEach on a FileList, we haven't ever noticed that because of the environment we use to develop, i believe, we indeed have forEach in the prototype of FileList, this is also the reason why this doesn't break on our website.
Surely we will take care of this, thanks for reporting ;)

**Comment by dhamaris** [comment]
No problem! Thank you for taking care, I close this ticket and will remove the extra tweak once it is added in future revisions
