### ISSUE TITLE
Harmonised Site Header - Group 1 - Missing site name in example when menu is present

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2215]
### Expected behavior
According to this https://ec.europa.eu/component-library/ec/harmonised-templates/group1/ 
I should see "Site Name" as in the image:
![image](https://user-images.githubusercontent.com/1392485/134935258-6d601689-2985-44b3-96e4-0eb29904282f.png)

### Actual behavior
But when accessing the playground, Site Name is missing: https://ec.europa.eu/component-library/playground/ec/?path=/story/components-site-headers-harmonised--group-1
Only when I deactivate Menu:
![image](https://user-images.githubusercontent.com/1392485/134935704-1cc53b6c-fa2c-4af0-beeb-51377c2a08f7.png)
Can I see the Site Name
![image](https://user-images.githubusercontent.com/1392485/134935836-c156febb-a3fb-4bfc-9cd1-74dee933cdfe.png)

**Comment by planctus** [comment]
Yes, it seems the implementation is not aligned with the usage page, in the template the site name is only printed when no menu is in place while the usage page shows an example of the site name visible together with the menu. A ticket has been created on our board for investigating this.
Thanks for reporting

**Comment by dhamaris** [comment]
Perfect, thank you!
