### ISSUE TITLE
ECLv3 - Search form label not showing

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2219]
### Expected behavior
I would expect the label to be visible as it is apparently present in the HTML markup from this example: [https://ec.europa.eu/component-library/playground/ec/?path=/story/components-forms-search-form--default](https://ec.europa.eu/component-library/playground/ec/?path=/story/components-forms-search-form--default)

```
<form class="ecl-search-form" role="search">
  <div class="ecl-form-group"><label for="search-input" class="ecl-form-label ecl-search-form__label">Search</label><input id="search-input" class="ecl-text-input ecl-text-input--m ecl-search-form__text-input" type="search" placeholder="Placeholder text" /></div><button class="ecl-button ecl-button--search ecl-search-form__button" type="submit" aria-label="Search"><span class="ecl-button__container"><span class="ecl-button__label" data-ecl-label="true">Search</span><svg class="ecl-icon ecl-icon--xs ecl-button__icon ecl-button__icon--after" focusable="false" aria-hidden="true" data-ecl-icon>
        <use xlink:href="static/media/icons.e477380f.svg#search"></use>
      </svg></span></button>
</form>
```

### Actual behavior
The label is not visible
![image](https://user-images.githubusercontent.com/1392485/135292737-1e910fda-1abb-4347-842d-e52d21c1c95a.png)

**Comment by planctus** [comment]
The label is hidden on purpose via css while it's present in the dom to preserve accessibility and compliance with the html forms specs.

**Comment by dhamaris** [comment]
Ok, thank you for the info, I close this ticket then.
