### ISSUE TITLE
ECLv3:  corner-arrow not visible in icons.svg (Pagination component)

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2220]
### Expected behavior
I would expect to find the svg for these arrow icons:
![image](https://user-images.githubusercontent.com/1392485/135489428-de491de7-dab2-49d2-a57a-3c81f0ecbbb7.png)
Located in the example in: static/media/icons.e477380f.svg#corner-arrow
In my dist package would be here: images/icons/sprites/icons.svg#corner-arrow'
### Actual behavior
No such icon is found in icons.svg.

Can you tell me how can I access corner-arrow? Thank you

**Comment by planctus** [comment]
The screenshot you attached here is loading the icon from the "same file" you have available, basically, so i don't necessarily know the reason for your issue, but could you specify which version of ECL are you using (guess 3.0.3) and could you also check for "corner-arrow" in the sprite svg, you should find it as an id.

**Comment by dhamaris** [comment]
I am using 3.0.3 version.
I found corner-arrow in the svg:
![image](https://user-images.githubusercontent.com/1392485/135599704-f70fcaaf-636f-4ded-924a-5ace53dfad38.png)


But still could not see it. 
![image](https://user-images.githubusercontent.com/1392485/135600128-2aeeed3e-cadf-4296-af6d-5c40d8554d50.png)
I tried with ui--corner-arrow instead and this one works, although this one is not present in the svg....strange
![image](https://user-images.githubusercontent.com/1392485/135600043-9559a567-fb54-423e-a24c-81f6ae2e644b.png)

**Comment by planctus** [comment]
mmh..this is really weird, it makes me think that you might be using the old svg sprite from v2 where indeed this icon was ui--corner-arrow.
Could you check that you are pointing to the right svg file, in your screenshot i see the file from v3 in a path and the one in the dom for the svg in an apparently different one.

**Comment by dhamaris** [comment]
It might be that, it is strange because I downloaded the right sprite but still could only see the ui--corner-arrow. 
It works now, thank you

**Comment by alexboss** [comment]
For information, not sure it's the same issue, but with ECL 3.4.0 we encounter similar issue.
The `corner-arrow` works fine for `icons.7b2977b3.svg` but not with `icons.ccfd2174.svg`
Cc: @planctus
