### ISSUE TITLE
Autocomplete for search

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2228]
We need a search input that suggests options as the user types the first characters.
We've seen that Multiselect allows that, but the problem is that we need to search from 90000 posibilities and it might not be very efficient to build such a huge Multiselect.
A search input with an autocomplete funciontality (as the multiselect) would be much more useful.

So our question is:
Are you planning on adding autocomplete to [Search  ](https://ec.europa.eu/component-library/ec/components/forms/search-form/code/) in the future?
If not, would it be possible for us to tweak it in order to add autocomplete to it?

**Comment by planctus** [comment]
Hello, an autocomplete functionality is not in the plans for ECL, this is tipically something you might want to have at an application level where the query is handled and the results of that can be narrowed by typing on the keyboard.
ECL could offer such a functionality only in a "limited" way, basing on an array of results "statically" passed to an input field by the "application", i will inform you in case anything like this will be considered.
You could surely add the autocomplete on your side, on the "search" or any other input of type text.

**Comment by dhamaris** [comment]
Ok thank you @planctus, I guess I will know eventually if you add autocomplete to your set of components, I close this ticket
