### ISSUE TITLE
Getting commit from solved issue

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2264]
Hi, would it be possible to get the commit where this issue was solved? We are trying to solve it in the 2.39 but we don't have time at the moment to migrate to the v3. Is that possible?

_Originally posted by @dhamaris in https://github.com/ec-europa/europa-component-library/issues/2123#issuecomment-977754961_

**Comment by emeryro** [comment]
Hello, if I'm not wrong, this fix has been introduced in https://github.com/ec-europa/europa-component-library/commit/ddddee8043e7a3cd25435e7d474c4a87df5dfd56
But as it is part of a more general update of the component, this may be quite hard to target specifically.
