### ISSUE TITLE
Modal dialog available for ECL?

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2294]
Hello,

I would like to use modal dialogs for confirmation messages, I didn't find any in the ECL so I am planning to use one from bootstrap, like this one:
![image](https://user-images.githubusercontent.com/1392485/147091855-e9592521-aad5-4fa4-8421-395a03f84962.png)

However, ideally I should only use ECL compliant components.
Are you planning on developing one for the ECL?

Thank you

**Comment by emeryro** [comment]
Hello,
There are some plans to add a modal feature in ECL, but no roadmap for it yet.
So for now you can use any other modal you want
