### ISSUE TITLE
moment not defined and ECL undefined

### ISSUE THREAD

**Issue by kilsedar** [ec-europa/europa-component-library#2313]
Hello,
using the code under 'How to use ECL' section at https://ec.europa.eu/component-library/ec/getting-started/, after adding ECL_VERSIONs and SRI hashes, I get two errors in the console: 'Uncaught ReferenceError: moment is not defined' & more importantly 'Uncaught TypeError: ECL is undefined'. I expect the template on the official page of the project to work. Eventually, we would like to use ECL in a Vue.js project, however first the simple HTML file should not raise errors. Version 2 runs without errors. How can I eliminate these errors? Thanks.

**Comment by planctus** [comment]
i agree that we should update a few doc to make this more evident, `moment.j`s is not bundled in the ECL script it needs to be loaded by the application, the information is avilable here, but should be moved in a more relevant file: https://github.com/ec-europa/europa-component-library/blob/v3-dev/docs/Migrating-v3.md

**Comment by unserializable** [comment]
This part from the docs does not sound too understandable

>  "Instruct minifier to preserve the UMD locally scoped 'moment' (default Pikaday module) variable in Pikaday in order to correctly reference the global 'moment' included separately from the ECL library bundle." 

What? What is UMD? Why would one use minifier with distro, e.g.  when `eUI` application wants to include ECL?

**Comment by planctus** [comment]
I'm sorry if this sounded cryptic, that text was added when we realised there was none, but it's directly copied from the builder script in ECL where it explains what ECL is doing regarding moment (UMD is a js module, technically what happens is that we preserve the moment namespace from being mangled when distributing our js). 
For you it's actually transparent, you just need to take care of loading moment.js in your application. ;)
