### ISSUE TITLE
Breakpoint mismatches between ECL documentation & ECL implementation (and also eUI)

### ISSUE THREAD

**Issue by unserializable** [ec-europa/europa-component-library#2317]
The breakpoints ECL uses seem to be here:
* https://github.com/ec-europa/europa-component-library/blob/v3-dev/src/themes/dev/maps/layout.scss

```
$breakpoint: (
  'xs': 0,
  's': 480px,
  'm': 768px,
  'l': 996px,
  'xl': 1140px,
) !default;
```
Which differ from the ones stated at the documentation at https://github.com/ec-europa/europa-component-library/tree/v3-dev/src/implementations/vanilla/layout/grid
 
```
Small | Bigger than 479px | @media (min-width: 480px)
Medium | Bigger than 767px | @media (min-width: 768px)
Large | Bigger than 991px | @media (min-width: 992px)
Extra large | Bigger than 1199px | @media (min-width: 1200px)
```

These also differ from eUI breakpoints (https://eui.ecdevops.eu/eui-showcase-ux-10.x/style-guide-legacy/general/responsive)

```
mobile	@media screen and (max-width: 767px)
tablet	@media screen and (min-width: 768px) and (max-width: 991px)
ltdesktop	@media screen and (max-width: 991px)
desktop	@media screen and (min-width: 992px) and (max-width: 1199px)
largedesktop	@media screen and (min-width: 1199px) 
```

### Expected behavior
Would expect ECL breakpoints to match in documentation and implementation. Ideally also to be the same as for `eUI`, especially the 991px vs 996px breakpoints seem like hair splitting :)

**Comment by emeryro** [comment]
Hello, I'm double checking the value with the designers, I'll let you know

**Comment by emeryro** [comment]
Correct values are the ones provided in the code (scss).
We will update the documentation (https://citnet.tech.ec.europa.eu/CITnet/jira/browse/FRONT-3540)
