### ISSUE TITLE
Multiselect grouping

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2326]
Hi, would it be possible that future releases of ECL add the possibility to group multiselect options? It would be something like this:

![image](https://user-images.githubusercontent.com/1392485/151970543-54ee74dd-f448-4289-85eb-6104b544b2d0.png)

We would need some kind of hierarchy in our multiselect, so at the moment we are doing it ourselves,  but it would be best if it could be available in the ECL itself.

**Comment by planctus** [comment]
Hello @dhamaris, it seems to me this would surely be an improvement of the current capabilities of the component. I'm just not sure about the real need for it, considering that this is the first time we receive this request. We will come back to you after evaluating this together with our product owners ;)

**Comment by dhamaris** [comment]
Thank you @planctus, I close this ticket, hopefully we hear from this request in the near future :)
