### ISSUE TITLE
There is visual regression in the multiselect component

### ISSUE THREAD

**Issue by ansergeyg** [ec-europa/europa-component-library#2335]
Hi there,
We have noticed that with the latest versions of the components there is an issue with multiselect component.

### Expected behavior
There should be the down-arrow on the right side of the field.
The state of the checked checboxes should not be blue.
### Actual behavior
There is no down-arrow on the right side of the field.
The state of the checked checkboxes looks broken,
### Steps to reproduce the issue
Just open this link:

https://ec.europa.eu/component-library/ec/components/forms/select/code/

Regards, Sergey

**Comment by planctus** [comment]
ops, thanks for reporting this...it seems the js is "broken", that icon is added via js..
