### ISSUE TITLE
Possible visual regression of the breadcrumb component

### ISSUE THREAD

**Issue by ansergeyg** [ec-europa/europa-component-library#2336]
Hi there,

We have noticed that with the latest version of the components there is a possible issue with the breadcrumb component.

### Expected behavior
Breadcrumb component had this css
`
border-bottom: 1px solid #bfd0e4;`

Which is showing the thin line under the breadcrumb
### Actual behavior
No it doesn't show this line.
### Steps to reproduce the issue
Just open this link
https://ec.europa.eu/component-library/ec/components/navigation/breadcrumb/code/

PS: If it is like that by a new design then disregard this issue.

Regards, Sergey

**Comment by planctus** [comment]
hi sergey, this was on purpose, a design update. ;)
