### ISSUE TITLE
Table - add filter on each column

### ISSUE THREAD

**Issue by emanuelaepure10** [ec-europa/europa-component-library#2357]
### Expected behavior
Would it be nice to have a filter box on each column of the table which would filter the table by selected column

### Actual behavior
There is just one filter box on the top of the table

### Steps to reproduce the issue
Just use a table and filer.

Thank you in advanced
Emanuela

**Comment by emeryro** [comment]
Hello, sorry for the delay.
ECL does not provide filter option for the tables. The only interactive behaviour is a column sorting (you can see it here https://ec.europa.eu/component-library/ec/components/table/code/)
So I assume that the single filter box you are refering to is something custom implemented on top of ECL.

**Comment by emanuelaepure10** [comment]
Hello @emeryro 

If you don't have such kind of feature in your future plans than probably we need to implement a custom function on top of ECL.

Thank you
Emanuela
