### ISSUE TITLE
Useful links for latest ECL versions

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2360]
Hi, can you add the section "Useful links" for latest ECLv3 versions?
Or is there any other way to get the packages? I tried with 

`npm i @ecl/preset-ec`

last time but I think something was different to the content of the zips. I am not sure anymore.
If the contents are the same, it is ok, if not please can you provide us with this section?

Thank you!

**Comment by planctus** [comment]
https://github.com/ec-europa/europa-component-library/releases/tag/v3.2.3 ;)
