### ISSUE TITLE
ecl-editor not available in ECL v3

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2387]
Hello, I am now migrating to the ECL V3 and I would love to have something like the ecl-editor class, Do you have something similar to apply styles to a section? I ask this because some of our sites have WYSIWYG managed by users that don't know about programming, and it would help apply styles to unorganized contents such as this.
It is related to this ticket:  #1577

**Comment by emeryro** [comment]
Hello, yes in ECL 3 the class is called  `.ecl`, but is it not part of the main ECL css.
If you want to use it, you have to include an optional css, called `ecl-ec|eu-default.css` (located in the `styles/optional` folder)
https://ec.europa.eu/component-library/ec/utilities/html-tag/usage/

**Comment by dhamaris** [comment]
Perfecto, thanks a lot! I close this ticket
