### ISSUE TITLE
Rendering the card title as link without having an actual link 

### ISSUE THREAD

**Issue by 22Alexandra** [ec-europa/europa-component-library#2504]
The `title` parameter of the Card component is following the Link component structure but card should allow regular strings as title too, not just links.
https://github.com/ec-europa/europa-component-library/blob/c9a78d9b503a12271e599bb2f57006d87e2823a9/src/implementations/twig/components/card/card.html.twig#L100

In the current implementation the markup would look like this:
`<a href="" class="ecl-link ecl-link--standalone">Example title</a>`

**Comment by planctus** [comment]
Yep, we removed the tile variant where we were rendering the title.label as a simple string, now the card uses this new "base" [template](https://github.com/ec-europa/europa-component-library/blob/v3-dev/src/implementations/twig/components/content-block/content-block.html.twig) we added in v3.3.0 that is currently rendering a link in any case.
I created this ticket: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/FRONT-3627

**Comment by emeryro** [comment]
Hi @22Alexandra , could you provide an example of page you currently have with card not having links?
