### ISSUE TITLE
Inconsistent behaviour of select / multiple select with or without svg4everybody - corner arrow icons don't display

### ISSUE THREAD

**Issue by alexboss** [ec-europa/europa-component-library#2656]
When copying / pasting content from https://ec.europa.eu/component-library/ec/components/forms/select/code/ into own code.

----

### Expected behavior

The corner arrow icon is displayed in the single select AND multiple select (with OR without `svg4everybody`).

### Actual behavior

Without  `svg4everybody`:
* 🔴 the single select does NOT display the corner arrow icon
* 🟢 the multiple select DOES display the corner arrow icon

With  `svg4everybody`:
* 🟢 the single select DOES display the corner arrow icon
* 🔴 the multiple select does NOT not display the corner arrow icon

(for these examples we used `7b2977b3` instead of `ccfd2174` - why? see https://github.com/ec-europa/europa-component-library/issues/2655 )

### Steps to reproduce the issue

Rename the file in `.html`:
[test-ecl-without-svg4everybody.html.txt](https://github.com/ec-europa/europa-component-library/files/9684184/test-ecl-without-svg4everybody.html.txt)
![without-svg4everybody](https://user-images.githubusercontent.com/1797662/193270995-86e3b8ac-6b76-4dd1-b549-63b05c22cadb.png)

Rename the file in `.html`:
[test-ecl-with-svg4everybody.html.txt](https://github.com/ec-europa/europa-component-library/files/9684185/test-ecl-with-svg4everybody.html.txt)
![with-svg4everybody](https://user-images.githubusercontent.com/1797662/193271023-2e698fc8-124a-449c-97d9-3da23dd13827.png)

----

Thank you and best regards.

Alexandre

**Comment by alexboss** [comment]
Thank you for your feedback on the Teams channel.

So, after using `icons.svg` from the CDN: https://cdn1.fpfis.tech.ec.europa.eu/ecl/v3.4.2/ec/images/icons/sprites/icons.svg 

----

### Expected behavior

The corner arrow icon is displayed in the single select AND multiple select (with OR without `svg4everybody`).

### Actual behavior

Without  `svg4everybody`:
* 🔴 the single select does NOT display the corner arrow icon
* 🟢 the multiple select DOES display the corner arrow icon

With  `svg4everybody`:
* 🔴 the single select DOES NOT display the corner arrow icon
* 🔴 the multiple select does NOT not display the corner arrow icon

### Steps to reproduce the issue

See https://ec.europa.eu/assets/ener/webtools/energy-union-indicators/test-ecl-without-svg4everybody.html 
![test-without-svg4everybody](https://user-images.githubusercontent.com/1797662/193558043-ad2088af-ee88-472c-b33d-b7da9c53fa68.png)

See https://ec.europa.eu/assets/ener/webtools/energy-union-indicators/test-ecl-with-svg4everybody.html
![test-with-svg4everybody](https://user-images.githubusercontent.com/1797662/193558082-24284ce1-5f5f-4f2f-afac-c8654c6fd6c8.png)

Actually, it looks like the headers sent with https://cdn1.fpfis.tech.ec.europa.eu/ecl/v3.4.2/ec/images/icons/sprites/icons.svg are so strict, it can't even be used on an Europa page, then not sure it could qualify as a CDN:
`Referrer Policy: strict-origin-when-cross-origin`

----

Thank you and best regards.

Alexandre

**Comment by planctus** [comment]
@alexboss, the issue is confirmed, when using the svg sprite from the cdn, simply calling svg4everybody() doesn't work for the corner-arrow icon. It's related to its source code, because it contains a `<use>` tag that gets processed by svg4everybody() breaking the code.
At the moment you can fix this by adding a validation function in the script call, this would work:
```
  svg4everybody({
    validate: function(src) { 
       return src.indexOf('#') !== 0 
    },
    polyfill: true
  });
```
But at the same time we will see if it's possible to change the source code of the involved icons, to avoid this and while sv4everybody makes it possible to load the svg from an external source, still the browser will show an error in the console, so generally speaking it would be better to always host the svg sprite in the domain where it is going to be used.

**Comment by planctus** [comment]
@alexboss, hello again, we just released [ECl v3.5.0](https://github.com/ec-europa/europa-component-library/releases/tag/v3.5.0) with new svg(s) for the icons that were failing when used directly from the CDN file.
This includes the corner-arrow, so now your tests, with `svg4everybody({ polyfill: true })` should work flawlessly, there are only two flags (in a different sprite file) that are still problematic.

**Comment by alexboss** [comment]
Excellent news, gonna try this today already, and report back, thank you.

**Comment by alexboss** [comment]
Thanks guys, excellent work, works fine now. Best regards. Alexandre.
