### ISSUE TITLE
Library page stopped working - Uncaught SyntaxError: expected property name, got end of script

### ISSUE THREAD

**Issue by arismag** [ec-europa/europa-component-library#2678]
### Expected behavior
Page on https://ec.europa.eu/component-library/ec/ should open and function.

### Actual behavior
Page not working https://ec.europa.eu/component-library/ec/

Console error message screenshot:
Uncaught SyntaxError: expected property name, got end of script:
![image](https://user-images.githubusercontent.com/10897246/199243986-9c74f63a-606c-430b-952e-b857c24fe82b.png)
Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_token

Page screenshot:
![image](https://user-images.githubusercontent.com/10897246/199244001-70c6a560-ffb7-483f-85f9-edf9160255b4.png)

### Steps to reproduce the issue
Navigate to any page under https://ec.europa.eu/component-library/ec/

**Comment by planctus** [comment]
Hello @arismag, we noticed this as well, but it's nothing depending on the library, but on the hosting of its website.
The issue has been fixed, it seems, now i can access all the ecl website versions, including all the archived ones.
If you confirm this please close this issue.
Thanks!

**Comment by arismag** [comment]
> Hello @arismag, we noticed this as well, but it's nothing depending on the library, but on the hosting of its website. The issue has been fixed, it seems, now i can access all the ecl website versions, including all the archived ones. If you confirm this please close this issue. Thanks!

@planctus thanks for the feedback, I confirm this too, it's working now smoothly ;)

Closing this!
