### ISSUE TITLE
Class ecl-page-header-harmonised__breadcrumb not reflected in catalog but needed for breadcrumb

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2774]
### Expected behavior
I am using ECL v3.6.0
When i get the example for a breadcrumb for an harmonized page header, i see this markup for nav tag [here](https://ec.europa.eu/component-library/playground/ec/?path=/story/components-site-wide-page-headers--harmonised):

`<nav class="ecl-breadcrumb ecl-page-header__breadcrumb" aria-label="You are here:" data-ecl-breadcrumb="true" data-ecl-auto-init="Breadcrumb">`

### Actual behavior
When I notice that my breadcrumb is too separated from the menu, I notice this rule in CSS:
```
.ecl-page-header-harmonised .ecl-container>:first-child:not(.ecl-page-header-harmonised__breadcrumb) {
    margin-top: 0;
    padding-top: 2rem;
}
```
### Steps to reproduce the issue
So I understand that the class ecl-page-header-harmonised__breadcrumb is also needed in nav tag, or else why is this rule needed?
If that is the case, this class should be in the catalog, otherwise, for harmonized I think that it really shoves down the breadcrumb a bit to much.

**Comment by planctus** [comment]
Hello @dhamaris, this selector is still in use for the [deprecated page header](https://ec.europa.eu/component-library/v3.6.0/playground/ec/?path=/story/deprecated-page-headers-harmonised--title), while it is not part of the definition of the [new page header](https://ec.europa.eu/component-library/v3.6.0/playground/ec/?path=/story/components-site-wide-page-headers--harmonised) which doesn't have any specific selector in the different "families" anymore, **the only available variant in the new page header is the negative** one, to be used in EC.
The reslulting look and feel of the new "harmonised" page header regarding the spacing between the breadcrumb and the meta element is this:
![image](https://user-images.githubusercontent.com/14326885/219305882-56f71e0d-f485-4019-83f9-d15d704f6854.png)

**Comment by dhamaris** [comment]
Ok @planctus, I was not using the meta and it seemed a lot of spacing between breadcrumb and title, but in the end we won't be using it since it is not needed.
Thank you, I close this ticket.
