### ISSUE TITLE
Multiple select list blocks form submission on Safari

### ISSUE THREAD

**Issue by kiwimind** [ec-europa/europa-component-library#2813]
### Expected behavior

When a multi select element is set to required, the form can be submitted.

### Actual behavior

When using Safari, nothing appears to happen when clicking submit. No console entries, no form submission.

### Steps to reproduce the issue

Using Safari 16.3 and the latest stable release (v3.7.1) add a taxonomy term reference field allowing for multiple items to be selected and set the field to be required.

Without the relevant EC classes being applied to trigger the multi select widget the form submits correctly, however when the classes are added it would appear that the form submission is being blocked. No entries appear in the console, no errors shown on screen. It's like it's failing the required nature of the select silently.

Worth noting this is on a custom theme rather than oe_theme, however I've checked that markup is correct, CSS and JS are being added correctly, etc. The field seems to be displaying correctly, just not allowing the form to submit.

**Comment by planctus** [comment]
Hello @kiwimind, we opened a ticket about this on our board. We have limited capabilities on testing with different browsers/OS but we will try to reproduce the issue on safari and find a solution if we confirm the issue.
Thanks, will report here updates on this.

**Comment by emeryro** [comment]
This issue will be fixed in ECL 3.8
