### ISSUE TITLE
Domain redirect issue

### ISSUE THREAD

**Issue by moaid500** [ec-europa/europa-component-library#2833]
### Expected behavior
the domain not working

### Actual behavior
this domain [HERE](https://cdn1.fpfis.tech.ec.europa.eu)
is showing error and most of time it redirects to [قصة عشق](https://es.3esk.co/)

**Comment by planctus** [comment]
Hello @moaid500, it's not clear the issue you have, that url is not supposed to be used as such, our resources are always inside the ecl folder and nested into a folder with the name of the version `https://cdn1.fpfis.tech.ec.europa.eu/ecl/{ecl-version}...`.
As you can see here the resources for 3.7.1 are accessible, this is the url to retrieve one of the EC css files hosted in the CDN: https://cdn1.fpfis.tech.ec.europa.eu/ecl/v3.7.1/ec/styles/optional/ecl-ec-default.css

**Comment by moaid500** [comment]
I see

> Hello @moaid500, it's not clear the issue you have, that url is not supposed to be used as such, our resources are always inside the ecl folder and nested into a folder with the name of the version `https://cdn1.fpfis.tech.ec.europa.eu/ecl/{ecl-version}...`. As you can see here the resources for 3.7.1 are accessible, this is the url to retrieve one of the EC css files hosted in the CDN: https://cdn1.fpfis.tech.ec.europa.eu/ecl/v3.7.1/ec/styles/optional/ecl-ec-default.css

I see . thanks for clearing it . I got the whole picture . 
it was just mis-understarding from my side . thanks and sorry
