### ISSUE TITLE
Body margin correction missing from ECLv2 and ECLv3

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2841]
Body has margin 8px, it says that it is applied by "user agent stylesheet":

![image](https://user-images.githubusercontent.com/1392485/233340992-8162728e-c1c0-4900-9b88-2fee29eca7f9.png)

In ECLv1, this correction was inside the ecl-preset-website.css:
![image](https://user-images.githubusercontent.com/1392485/233341276-acb6337f-b905-439c-a328-8fd6c36a4bf5.png)

Since ECLv2 this is not the case, so we have to add it in a separate css:
![image](https://user-images.githubusercontent.com/1392485/233340396-6ab3f2d4-d816-4850-affc-738d93711fbd.png)

Why is this correction no longer incorporated into ecl?

Thank you

**Comment by planctus** [comment]
Hello @dhamaris in ECL v3 there is a preset, **@ecl/preset-reset**, meant also for that, together with the inclusion of normalize.css:
https://github.com/ec-europa/europa-component-library/blob/v3-dev/src/presets/reset/src/reset.scss

not sure on how you fetch the ECL resources, the one mentioned before is the name of the npm package, but you also get this in the CDN in the "optional" folder inside the style folder as well as in the same path in the **@ecl/preset-ec** and **@ecl/preset-eu** packages. 
Thanks
