### ISSUE TITLE
Suggestion to provide a DOCTYPE in the Getting started / How to use ECL snippets

### ISSUE THREAD

**Issue by alexboss** [ec-europa/europa-component-library#2849]
### Expected behavior

`<!DOCTYPE html>` provided in the Getting Started snippet.

### Actual behavior

No `<!DOCTYPE html>` provided in the Getting Started snippet.

### Steps to reproduce the issue

Go to https://ec.europa.eu/component-library/eu/getting-started/ or https://ec.europa.eu/component-library/ec/getting-started/
Check § How to use ECL 

### Rationale

According to https://developer.mozilla.org/en-US/docs/Glossary/Doctype

> In HTML, the doctype is the required "<!DOCTYPE html>" preamble found at the top of all documents. Its sole purpose is to prevent a browser from switching into so-called "quirks mode" when rendering a document; that is, the "<!DOCTYPE html>" doctype ensures that the browser makes a best-effort attempt at following the relevant specifications, rather than using a different rendering mode that is incompatible with some specifications.

**Comment by planctus** [comment]
Hi @alexboss, that example is not really meant as a guide to write a proper html page, but only to see how to manage the ECL resources inside of it. At the same time there is no particular reason for not having a doctype definition in the example, so we will add it..  ;)

**Comment by planctus** [comment]
https://ec.europa.eu/component-library/ec/getting-started/
