### ISSUE TITLE
Table sort submitting form when clicking on icon

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2889]
I am using ECL v3.8.2. I have the sorting table inside a form, and when I click on the whole name it works properly. However, when clicking right on the arrow icon:
![image](https://github.com/ec-europa/europa-component-library/assets/1392485/57bd93cf-836c-4d2c-8e77-e15bb840a48e)
It seems that the event gets propagated and submits the form, and this is not desirable.

I think it is related with somehow the icons firing default button behavior, because if I set a breakpoint here:

![image](https://github.com/ec-europa/europa-component-library/assets/1392485/3ae9cc37-9808-4c46-bbcf-f30f195bd17b)

And call event.preventDefault(), it works.

**Comment by planctus** [comment]
Thanks for creating this issue, @dhamaris,  we will prevent the form submission in the next release.

**Comment by dhamaris** [comment]
Perfect @planctus, thank you, I close this ticket and wait for next release.
