### ISSUE TITLE
Language selector behind the Banner

### ISSUE THREAD

**Issue by marioheber** [ec-europa/europa-component-library#2953]
The z-index of the Banner and Language selector are conflicting.
I fixed by overwriting the Banner's z-index to 1, instead 2 as it's by default: https://github.com/ec-europa/europa-component-library/blob/ea5d31604684cbb5e729f4641897de020123ae8b/src/implementations/vanilla/components/banner/_banner.scss#L305

The screenshot of the issue:
![image](https://github.com/ec-europa/europa-component-library/assets/1019420/312c6523-8e3a-4c29-83a1-95d23d15f745)

**Comment by planctus** [comment]
fixed in https://github.com/ec-europa/europa-component-library/releases/tag/v3.9.0
