### ISSUE TITLE
Various issues with Tabs

### ISSUE THREAD

**Issue by cstrobbe** [ec-europa/europa-component-library#2977]
When using a tabbed interface, the expected **keyboard interaction** is as follows:
* Pressing `Tab` moves focus to the tabbed interface. Pressing `Tab` moves focus away again. This currently works correctly.
* Pressing the right and left arrows moves focus between the tabs. This currently works correctly.
* Pressing `Enter` or `Space` opens or activates the tab if receiving focus did not open it already. At the moment however, `Space` does nothing, whereas `Enter` takes you to a dummy page. It is not clear whether this is due to missing keyevent listeners or due to the fact that there is no content in the tabs, so the intended behaviour is not fully demonstrated. However, since keyboard interaction does not change the values of the `aria-selected` attributes (or the `tabindex=-1`), I assume there is not yet any keyboard support for changing the active tab.
* Pressing `Home` should move focus to the first tab. It looks as if this is currently not implemented.
* Pressing `End` should move focus to the last tab. It looks as if this is currently not implemented.

I also have a few comments about the elements and WAI-ARIA attributes;
* There is no need for a `nav` to wrap around the Tabs. Due to `nav`, screen readers announce a navigation landmark, which is not the expected behaviour.
* There is no `aria-controls` attribute in the `a` elements with `role="tab"`.
* The content of each of the tabpanels is not in a `div` or other element with the attributes `role="tabpanel"` and `aria-labelledby="ID"` (with ID referring to the corresponding `a` with `role="tab"`.

For an example, see [Example of Tabs with Manual Activation](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/) at the W3C.

**Comment by planctus** [comment]
We are pretty aware of the critical points regarding tabs accessibility, the truth is that there wasn't and still there isn't a clear direction to take. 
The page you mentioned was accessed many times in the past months but it still has this big warning that doesn't really make this example look like something to be reproduced at the moment:
`The code in this example is not intended for production environments. Before using it for any purpose, read this to understand why.`
We are not even testing this component about accessibilty anymore because we don't know how to put everything together to fullfill the axe constraints, basically.

**Comment by cstrobbe** [comment]
> The page you mentioned was accessed many times in the past months but it still has this big warning that doesn't really make this example look like something to be reproduced at the moment:
> `The code in this example is not intended for production environments. Before using it for any purpose, read this to understand why.`
> We are not even testing this component about accessibilty anymore because we don't know how to put everything together to fullfill the axe constraints, basically.

I am not simply referring to that example because it's on the W3C's website, but because I have tested it for keyboard accessibility and with screen readers. It works in the browser and AT combinations I have tested it with. The current ECL Tabs don't. If you reject the suggestions from the W3C example because of the "not intended for production environments", shouldn't the ECL Tabs be withdrawn for the reason that it is not keyboard accessible? Lack of keyboard accessibility is a [blocking issue for EC DGs or units who want to publish a new site](https://commission.europa.eu/resources-partners/europa-web-guide/design-content-and-development/accessibility/testing-early-and-regularly/accessibility-report_en), for example.
