### ISSUE TITLE
CDN down?

### ISSUE THREAD

**Issue by pitommasi** [ec-europa/europa-component-library#2984]
### Expected behavior
the website loads the assets from the CDN

### Actual behavior
no resources are loaded

### Steps to reproduce the issue
navigate to any link to the CDN (e.g.: https://cdn1.fpfis.tech.ec.europa.eu)

From this morning, the CDN to fetch the js and css from to be embedded in our website (https://ghsl.jrc.ec.europa.eu/) is not responding anymore (tried cdn1, 2, 3 and 4).
I've applied a temporary fix by downloading the files but I'd like to reinstate the CDN links ASAP.

Could someone please look into it?

Thanks

**Comment by planctus** [comment]
It is, but it's not managed by the ECL team, there is an ongoing investigation about the issue. 
Thanks

**Comment by planctus** [comment]
Issue has been solved, feel free to close this issue when you confirm this. Thanks @pitommasi , and sorry for the problem, although it was totally unrelated to us.
