### ISSUE TITLE
vite warning for start/end instead of flex-start/flex-end css

### ISSUE THREAD

**Issue by lagamura** [ec-europa/europa-component-library#3116]
### Expected behavior
The library should be used in frameworks like Nuxt without warnings from Vite

### Actual behavior
Vite throws the following when loading the css files '@ecl/preset-ec/dist/styles/ecl-ec.css', '@ecl/preset-ec/dist/styles/ecl-ec-print.css' :`WARN  [vite:css] start value has mixed support, consider using flex-start instead.` and logs the whole file in the terminal.
 
In similar case faced from the nuxt team here: [css-start-bug](https://github.com/nuxt/devtools/pull/369/commits/09f163636f9c6f431e8614ee868d77f762a13559)
They just updated `start` to `flex-start`. I also tried manually replacing the css files and the warning disappears. 

### Steps to reproduce the issue
Setup a nuxt project via `npx nuxi@latest init <project-name>`
Install ecl/preset-ec: `npm i @ecl/preset-ec`
Create a component and import the css file: `import '@ecl/preset-ec/dist/styles/ecl-ec.css'`
run the local server: `npm run dev`

I am not so experienced In contributing but if the problem can be resolved just by updating the css files, I can try to create a pull request and update the *start* and *end* attributes.

**Comment by planctus** [comment]
Hello @lagamura, i guess that the vite warning is only concerning the usage of the value "start" and "end" as a flex display option, we do use "start" for instance for supporting LTR/RTL as a text-alignment value which i guess it's perfectly fine for vite.
So, we will replace the usage of start and end when in a flex context. Will post here the compiled css for you to test it before mergin the pull request.

**Comment by planctus** [comment]
[no-start-end.zip](https://github.com/ec-europa/europa-component-library/files/13486291/no-start-end.zip)
 Hi, @lagamura, in this zip file you find the two main css for EC with the replacement of the "start" and "end" values when used in a flex context.
Could you give it a try and see if the warnings are gone?

**Comment by lagamura** [comment]
@planctus Thanks for the response, I just tried it and vite is fine with the updated css files.
