### ISSUE TITLE
Broken Eu bundled CSS

### ISSUE THREAD

**Issue by hewok** [ec-europa/europa-component-library#3277]
### ECL Version
v4.0.0

### Actual behavior
In the file `ecl-eu.css`, loaded from the package `@ecl/preset-eu`, I get this error:

`.ecl-menu--light:not(.ecl-menu--forced-mobile) .ecl-menu__items-previous:not(.ecl-menu__item--current):after{height:calc(100% + 2 *);right:-;top:-}.ecl-menu--light:not(.ecl-menu--forced-mobile) .ecl-menu__items-next:not(.ecl-menu__item--current):before{height:calc(100% + 2 *);left:-;top:-}`

From line 6 col 162990 until line 6 col 163148.

### Expected behavior
Load CSS without error

### Steps to reproduce the issue
With npm load [`"@ecl/preset-eu": "^4.0.0"`](https://www.npmjs.com/package/@ecl/preset-eu) as a dependency, then load the `node_modules\@ecl\preset-eu\dist\styles\ecl-eu.css` into your HTML page.

**Comment by planctus** [comment]
@hewok, we are about to release a patch release v4.0.1 that will fix this, thanks for reporting it and sorry for the issues it caused.

**Comment by hewok** [comment]
Thank you very much @planctus
