### ISSUE TITLE
Carousel not working with Prev - Next button icons after update from 4.0.1 to 4.1.1

### ISSUE THREAD

**Issue by theGiuMac** [ec-europa/europa-component-library#3344]
### Expected behavior

In 4.0.1, the carousel was correctly responding to previous and next slide actions, under the ECL jargon.

### Actual behavior

After upgrading to 4.1.1, the carousel buttons simply do not trigger any action, and only autoplay works

### Steps to reproduce the issue

For Prev, before the .ecl-carousel__container class:

`<button class="ecl-button ecl-button--ghost ecl-carousel__prev ecl-button--icon-only" type="button">
            <span class="ecl-button__container">
                <span class="ecl-button__label" data-ecl-label="true">Previous slides</span>
                <svg class="ecl-icon ecl-icon--m ecl-icon--rotate-270 ecl-button__icon" focusable="false" aria-hidden="true" data-ecl-icon>
                    <use xlink:href="/assets/ec-preset-ecl-v4.1.1/images/icons/sprites/icons.svg#corner-arrow"></use>
                </svg>
            </span>
        </button>`

For Next, after the .ecl-carousel__container class:

`<button class="ecl-button ecl-button--ghost ecl-carousel__next ecl-button--icon-only" type="button">
            <span class="ecl-button__container">
                <span class="ecl-button__label" data-ecl-label="true">Next slides</span>
                <svg class="ecl-icon ecl-icon--m ecl-icon--rotate-90 ecl-button__icon" focusable="false" aria-hidden="true" data-ecl-icon>
                    <use xlink:href="/assets/ec-preset-ecl-v4.1.1/images/icons/sprites/icons.svg#corner-arrow"></use>
                </svg>
            </span>
        </button>`

**Comment by emeryro** [comment]
Hello,
The previous / next buttons for the carousel have been removed in ECL 4.1.0. This was done in [this pull request](https://github.com/ec-europa/europa-component-library/pull/3291)
The main carousel navigation is still there (with number buttons), and the autoplay.
I assume that you are not using the twig template, so the change may not have been detected. You can remove the prev / next buttons from your markup
