### ISSUE TITLE
Multi header table needs CSS fix for border-inline-end-color

### ISSUE THREAD

**Issue by joarod-eu** [ec-europa/europa-component-library#3582]
### Expected behavior
When rendering a Multi header table, we expect to have all the cells in the header with the right border color.

### Actual behavior
The current Multi header table has a color bug with the last child cell in the `<thead>` . It has a border right with the wrong color:
![image](https://github.com/user-attachments/assets/da1f4393-517f-4a1f-b7de-e6b83bc6edb1)

### Steps to reproduce the issue
Just visit the ECL official website and check the Multi header example:
https://ec.europa.eu/component-library/ec/components/table/code/

### Current fix
Adding this style for the last child in a Multi header table do the job:
`border-inline-end-color: var(--c-n-160);`

**Comment by emeryro** [comment]
Hello, 
Thanks for reporting this. I can reproduce it on Firefox (Chrome is fine).
We will check that

**Comment by joarod-eu** [comment]
Sorry to forget to add the browser type in the description.

As you confirmed, I tested on Safari, Edge, Chrome and works as expected. The problem only appears on Firefox (last version v129 and ESR v115).

Thanks

**Comment by joarod-eu** [comment]
Why this issue was closed?
I can see in the last version 4.6.5 that the problem is still there.
https://ec.europa.eu/component-library/ec/components/table/code/

@planctus any reason?
*Feel free to discuss via Teams if preferred
