### ISSUE TITLE
Delete an uploaded file in file-upload component

### ISSUE THREAD

**Issue by Migorcajo** [ec-europa/europa-component-library#3591]
Hello, I have a form with a file-upload component. 
When I attach a file, I have no option to delete it (when I haven't sent the form) unless I click on "Replace" and don't select a file.

I have check the API and the documentation, and I have seen this [https://v4-dev--europa-component-library.netlify.app/playground/ec/?path=/story/compositions-file-upload-status--default](url) but not sure how to use it.

I have made a solution using javascript and adding some html dynamically, but I would like to find a more 'elegant' solution.
I'm missing something or there is no other way right now to do that task?

Thank you in advance!

**Comment by planctus** [comment]
Hi @Migorcajo, our file upload is purely a UI component, the "replace file" is only a UI element looking like a button placed on top of the default file input, so it simply works as the default file input works in HTML.
To remove a file you previously selected you need to click again on the button and not select anything.

As you noticed we have a more complex example related to the multiple files upload, but that is only an example, the implementation is up to you, we show you how it could look like and the ECL markup for that.
So i think that your current solution might actually be good enough, if it works, and if you use the markup in our example you also have a reliable mock to replicate ;)

**Comment by Migorcajo** [comment]
Hello @planctus, thanks for your answer. 

In my solution I had to do a thing I didn't like very much, because I added a new onChange event to the upload-file that waits until the "li element"  is added to the code. So, there is any way I can manage or override the initial onChange event associated? I've seen in the API the handleChange, but not sure how to use it.

Than you!

**Comment by planctus** [comment]
well, you can override pretty much everything in our class, but then you would have to reproduce what we do in order to further extend it.
This is a good use case for a custom event to be defined by the file upload class so that you can register a callback to it, we would emit this event at the end of our handleChange() and with that you can reliably count on the fact that the markup is in place.
We will do this, but it will be released in the next weeks, for the moment you can probably live with the solution you have.

**Comment by Migorcajo** [comment]
Thank you again @planctus. 
I will keep an eye on the updates, and mantain my solution until that!
