### ISSUE TITLE
In-page navigation odd behaviour when Drupal Toolbar is present

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#3608]
Hello, I am using ECL 4.6.3 and I am finding an odd behaviour when using inpage navigation with toolbar from Drupal. When I click on a menu link, the one that gets the focus is the one above it. In the example I clicked on "Accprdion 3"
 but it was as tthough I clicked "accordion 2". And so with every link, the one above gets selected ![Screenshot from 2024-09-05 17-27-53](https://github.com/user-attachments/assets/c3b64504-6ee8-4236-a122-eac5903b5e2f)
 
This does not happen when i am not administrator, and i don't see this sticky toolbar from Drupal:

![image](https://github.com/user-attachments/assets/0bea37fa-361f-4cb4-8987-e19d0d2255ce)

The point in code where I think that the wrong element gets selected is this one, so I thought it must have to do with the toolbar disturbing this functionality of selecting an element when its heading is withing a threshold in the viewport. 
![image](https://github.com/user-attachments/assets/64edcfde-bf7a-435f-9e47-957cbf14f0ee)
![image](https://github.com/user-attachments/assets/a151a2dc-aad5-46dd-9c63-db445e905eb9)

Can you confirm if that is the case? Or otherwise where could be the issue here. 
Thanks

**Comment by planctus** [comment]
Hello @dhamaris, being this an issue that you experience when logged in in your Drupal website, we cannot directly offer you support, we would need to reproduce somehow the issue you have in a different environment for being able to help you. Do you have any environment where you could give us access as "registered users"..? I'd say this is very minor, anyway, the inpage is meant to work as a navigation element for the end user, this issue you experience, being limited to the logged in user, it's something we might not necessarily have to support, but let's see if we can identify the reason for this.

**Comment by dhamaris** [comment]
Thank you @planctus, next week I will try to provide you with a testing URL to see if you can identify the problem. As you say, it is a minor thing, thank you for taking a look into it.

**Comment by dhamaris** [comment]
Hello @planctus, can you check if you can access the following URL?

https://euromod-eclv4.apps.ocpt.jrc.cec.eu.int/my-ecl-page-testing

Let me know if you can connect to it and I will show you how to reproduce the issue.
Thank you

**Comment by planctus** [comment]
mmh..no, i couldn't, tried from the remote desktop as well, there i get a "timeout", the server took too long to respond.

**Comment by dhamaris** [comment]
By remote desktop you mean the VPN using the proxy from the EC? I think these links are visible on the Welcome network, do you have access to them?

**Comment by dhamaris** [comment]
Hi, since this problem only happens to some types of admins, I think we will have to wait until we put it into production so that you can reproduce it, thanks!
