### ISSUE TITLE
Required symbol (*) for form fields not aligned with text label

### ISSUE THREAD

**Issue by joarod-eu** [ec-europa/europa-component-library#3609]
### Expected behavior
The red star symbol (*) should be at the end of the text in the label/legend when it has a long text (two or more lines).

### Actual behavior
The symbol stays at the middle of the label, what is odd in terms of UI. Also several users already point it out as an error in the html formatting (but it's due to a CSS attribute).

### Steps to reproduce the issue
Add a long text in a label/legend for a mandatory field. Example:
![image](https://github.com/user-attachments/assets/36e47b3d-2fef-4de2-a85a-89f9c911b91c)

### Fix
Using Display: Block or Display: Inline or Display: Inline-block will render the symbol (*) in the right place.

**Comment by planctus** [comment]
Thanks for reporting this, @joarod-eu will be fixed as soon as possible

**Comment by emeryro** [comment]
Closing this issue. 
Fixed in https://github.com/ec-europa/europa-component-library/pull/3611
Released in ECL 4.7.0
