### ISSUE TITLE
Is it possible to see the current version of ECL?

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#3655]
Hello, there is something that would help us developers save time and energy.

Can you implements a method (or property) "version" for getting the current ECL version? 
It should be invokable from the ECL object, so that we can check the version quickly from the browser console.
At the moment we have to find the ecl-ec.js and see the comments at the beginning of the file, but sometimes the code is compressed or merged and it is more difficult. 

We manage a lot of Drupal sites with different versions, it would help a lot.

Thanks

**Comment by planctus** [comment]
Like this @dhamaris..? :) 
https://ecl-preview-3657--europa-component-library.netlify.app/playground/ec/?path=/story/components-blockquote--default&globals=viewport:responsive

Thanks for the idea, this is actually very handy for us as well.

**Comment by dhamaris** [comment]
Hi! I don't see what you mean on the link, sorry. I just see the quote widget

**Comment by planctus** [comment]
Just run ECL.version as you suggested in your console :)

**Comment by dhamaris** [comment]
I still don't get it, it complains that ECL object does not exist :/

![image](https://github.com/user-attachments/assets/e030a950-abc5-48a3-9331-31854de66c45)

**Comment by planctus** [comment]
well, @dhamaris, in our storybook the rendered content is in an iframe, so in your inspector you should select this iframe, not the main window, to be able to play with the ECL object.
Anyway, easier to show you directly the result: 
![image](https://github.com/user-attachments/assets/56c11dfa-3667-46cf-a480-667d9956abf9)

**Comment by dhamaris** [comment]
Oh I see now! I just learned to use that selector on the chrome console, thank you!
