### ISSUE TITLE
Different alignment EC/EU for modal dialog header

### ISSUE THREAD

**Issue by wiibaa** [ec-europa/europa-component-library#3658]
### Expected behavior

I would expect that both EC/EU dialogs have the same alignment in header

### Actual behavior

EC (from https://ec.europa.eu/component-library/playground/ec/?path=/story/components-modal--default&globals=viewport:responsive)
![image](https://github.com/user-attachments/assets/8aa660e2-d568-4bd5-9a03-766c3189bdb7)

EU (from https://ec.europa.eu/component-library/playground/eu/?path=/story/components-modal--default&globals=viewport:responsive)
![image](https://github.com/user-attachments/assets/715cb960-893e-4820-b591-66ed460f42cb)

### Steps to reproduce the issue

Immediate, visible in playground

**Comment by emeryro** [comment]
Hello, indeed, the spacing are not the same between EC and EU, and so the content is not placed exactly at the same position.
But this is the expected design. In both cases, the buttons is not supposed to be aligned with the (optional) title, it is placed absolutely from the top right corner (even in on EU it is closer to be aligned)

**Comment by wiibaa** [comment]
Thanks for confirmation. It helps!
