### ISSUE TITLE
Menu / Mega menu - HTML code missing

### ISSUE THREAD

**Issue by joarod-eu** [ec-europa/europa-component-library#3716]
### Expected behavior
Checking the **Menu**, **Mega menu** and **Site header** components, I want to see the HTML code in the **Showcase** tab. The rendered example should match with the current HTML code displayed in this tab.

### Actual behavior
The menu (blue bar) it renders fine, but the code doesn't show this part in any of the three components, I can only see the header code without the menu. However the playground/storybook has this HTML code as expected.

### Steps to reproduce the issue
Visit any of these links and scroll down to check the HTML code. Click on "Show more" and you will see that the code for the menu is missing.
https://ec.europa.eu/component-library/ec/components/navigation/mega-menu/code/
https://ec.europa.eu/component-library/ec/components/navigation/menu/code/
https://ec.europa.eu/component-library/ec/components/site-wide/site-header/code/

*Same code missing for EU components

**Comment by planctus** [comment]
Thanks for reporting this, will be fixed in the next ECL release.

**Comment by emeryro** [comment]
Fixed in version 4.9.0
