### ISSUE TITLE
Question about custom footers

### ISSUE THREAD

**Issue by giorgialodi** [ec-europa/europa-component-library#481]
The documentation for the custom footer states "never add the site map". However, the provided example/demo includes a "site map" link in the custom footer. 
We are currently developing a web application for an EC's DG and we would like to understand how we have to deal with it in order to be compliant with the general guidelines.

**Comment by kalinchernev** [comment]
@giorgialodi documentation pages are mostly guidelines as well as demos.
The custom footer is an optional part where DGs add links to (literally) custom resources not covered by the global one. 

The custom footer usually contains elements which depend on case by case scenarios for specific DGs. To get this information, you'd normally have to inquire the site owner or other responsible for the migration/transformation.

For which target project is the question about?

**Comment by kalinchernev** [comment]
Dear @giorgialodi documentation about custom footers has been recently updated with details about the site map. The point is, you can include a link to the site map, but not the full site map.
If you have further questions, please feel free to re-open the issue or address the question with the usual internal communication channels like Jira.

**Comment by giorgialodi** [comment]
Dear @kalinchernev thanks a lot for your answer. We will definitely have a look at the new version of the documentation. BTW: the web site that we are constructing is a web application for DG MARE on commercial designations of fishery and aquaculture products marketed in the EU.
