### ISSUE TITLE
Inpage navigation not working correctly in mobile layout

### ISSUE THREAD

**Issue by jcastro-malet** [ec-europa/europa-component-library#593]
Hello
I've found this problem with my code, but I checked that it also happens in the demo. The test was done with Google Chrome 62

### Expected behavior
When you access an inpage navigation using a mobile device, a sticky select-item should appear, letting you navigate through the different headers. I understand this is the expected behaviour, because as I explain later, I've been able to see this behaviour at some points.

### Actual behavior
Right now if you access the demo from a mobile device, the select-item doesn't appear.
The demo only shows this select-item if you access the page from a normal browser, and then change the page's size, for example using the development tools of Google Chrome

### Steps to reproduce the issue
**Case 1:**
- Access the inpage navigation demo from a mobile device: https://ec-europa.github.io/europa-component-library/components/preview/ecl-navigation-inpages
- Go up and down with the scroll, checking that the select-item doesn't appear.

**Case 2:**
- Access the inpage navigation demo using Google Chrome: https://ec-europa.github.io/europa-component-library/components/preview/ecl-navigation-inpages
- Open the development tools (F12). Press Ctrl-Shift-M to change to mobile layout
- Go up and down with the scroll, checking that the select-item used for navigation appears in the upper part of the page.
- Now refresh the page (F5)
- The select-item disappears, so you can't navigate through the headers.

Thank you very much

**Comment by yhuard** [comment]
Thank you @jcastro-malet for reporting this issue! I can confirm I can reproduce it.
We have added this issue to our backlog and we will keep you posted on any future developments.

**Comment by jcastro-malet** [comment]
@yhuard thank you very much

**Comment by jcastro-malet** [comment]
I tested the solution, but I've seen that although with this change the mobile version starts working, I'm finding some problems with IE11. When the left side of the inpage navigation goes sticky, then the right side moves to the left, taking the same space as the sticky block.
The only solution I've found is going back to the original code, that didn't worked with the mobile layout.

**Comment by yhuard** [comment]
You're right... On IE (no `position: sticky` support), the left column gets `position: absolute` when sticky, that's why the right column takes its place.

I'll try to find a better solution. Thanks for reporting it (again)

**Comment by yhuard** [comment]
I've come up with 2 "solutions":
- the first one: we acknowledge that IE doesn't support `position: sticky` and we consider this behavior as an optional enhancement (-> progressive enhancement)
- the second solution: we replace `stickybits` with `stickyfilljs`. It acts more like a polyfill and has the advantage of correctly handling the div width.

In both cases, we can't rely on `stickybits`' classes anymore for the mobile behavior. This has been fixed in the first PR, not in the second (yet).

I guess we will go for the second one... right @degliwe @kalinchernev @emeryro @raduchiriac?

**Comment by kalinchernev** [comment]
For me, personally, both solutions are acceptable.

Not only sticky behavior could be accepted as a progressive enhancement, but also support for IE11 is not so valuable of an investment as usage is very low.

Regarding the second option, `stickyfilljs` is result #1 when searching for a polyfill for the sticky behavior, so if this behavior is business critical, the solution provided is definitely the best one in terms of implementing third party helpers.

**Comment by yhuard** [comment]
Hi @jcastro-malet 

Can you tell me if the updated https://ec-europa.github.io/europa-component-library/ec/components/detail/ec-component-inpage-navigation resolves your issue? thanks

**Comment by jcastro-malet** [comment]
Hello @yhuard 
I haven't been able to test it, because I've seen that the new release changes the name of some css classes, and I still have to adapt my website to the new names to be able to test it. Whenever I can check it, I'll reply again.

Thanks.
