### ISSUE TITLE
Problems with IE10

### ISSUE THREAD

**Issue by jcastro-malet** [ec-europa/europa-component-library#624]
Hello
I'm not sure about the compatibily matrix, but as IE10 is still used by a lot of users, I think all the components should work with this browser.

### Expected behavior
The components should look the same with different browsers.

### Actual behavior
The "date" component is shown in a different way when IE10 is used. The labels are shown horizontally instead of vertically.
I've found the same problem with other components that use the property "display: flex", but I can't reproduce this other problems within the demo.

### Steps to reproduce the issue
Open https://ec-europa.github.io/europa-component-library/components/preview/ecl-list-items#list-item-3 with IE10
Open the development tools and select IE10 to render the page
The date component should change and show the labels horizontally

The only way I've found to fix this has been adding the next code, but I understand maybe it's not the right solution:
.ecl-date-block__body span {
	display: block;
	text-align: center;
}

Thank you very much

**Comment by degliwe** [comment]
Thank you for your report.
About the browser support, we aim to be compliant with the IPG recommandation (IE11+)
http://ec.europa.eu/ipg/standards/browsers/index_en.htm#section_2
