### ISSUE TITLE
404 when opening a component page

### ISSUE THREAD

**Issue by pitommasi** [ec-europa/europa-component-library#631]
### Expected behavior
Get the component page on github

### Actual behavior
404 page 

### Steps to reproduce the issue
Click on any component

**Comment by pitommasi** [comment]
The [grid page](https://github.com/ec-europa/europa-component-library/blob/next/framework/layout/grid/ecl-grid), for instance...

**Comment by yhuard** [comment]
Ok, so you are talking about the links in the root README file. They are not up-to-date and PR #633 will remove them. 

May I ask you what kind of information you were looking for when you first clicked on the link? Knowing this, we may improve our docs

**Comment by pitommasi** [comment]
Yes, basically, I need to know how to use the components in my website.

**Comment by yhuard** [comment]
First, the link you are looking for is: https://github.com/ec-europa/europa-component-library/tree/master/framework/layout/ecl-grid

The ECL Grid is Bootstrap 4's grid with our own naming convention. Basically, the only difference is that we add the `.ecl-` prefix to the CSS class names. The best place to learn about how the grid works is https://getbootstrap.com/docs/4.0/layout/grid/ On our side, we will have to spend some time enriching the documentation, it's something that has already been reported by other people and we will need to take care of it.

Do you have any other question or remark? Or can I close this issue?

**Comment by pitommasi** [comment]
Thanks, I'd gladly say "case closed" ;-)
