### ISSUE TITLE
Is there any documentation on how to use ECL Components from a Java Spring project?

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#689]
Hi, do you know if there is or will be a way to consume ECL components in a Java project using Spring MVC? Any documentation on this? The only reference I found so far was:

https://fractal.build/guide/integration/including

Thank you.

**Comment by degliwe** [comment]
Thank you for the question.
ECL components are technology agnostic so it means you should be able to integrate them with pretty much anything (including Java)

Fractal is the tool we use to build the online styleguide but it isn't part of the component (you don't need to know about fractal to use ECL)

You can start experimenting by downloading a release https://github.com/ec-europa/europa-component-library/releases it contains all the compiled css, js and assets you need.

Then look online on the styleguide for markup templates:
https://ec-europa.github.io/europa-component-library/ec/

Please confirm if it solves your issue.

**Comment by dhamaris** [comment]
Thank you, this solves my issue, you can close this ticket.
