### ISSUE TITLE
Spring tag <form:checkbox> not rendered properly

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#718]
### Expected behavior
 Hi, when rendering a spring checkbox, its color won't change when clicking it. Spring checkbox are rendered in html not the same as the checkbox from the demo, that is:

```
<label class="ecl-form-label ecl-checkbox">
	<input id="runmacroSimulation" name="runMacroSimulation" class="ecl-checkbox__input ecl-u-sr-only macroSimulationCheckbox" type="checkbox" value="true">
        <input type="hidden" name="_runMacroSimulation" value="on">
	<span class="ecl-checkbox__label ecl-u-fs-xs run-micro-simulation-message checkbox-micro- 
           simulation">Run medium-term macro impact</span>
</label>
```

The structure expected, and the one used in the demo is this one:

```
<label class="ecl-form-label ecl-checkbox">
       <input class="ecl-checkbox__input ecl-u-sr-only" type="checkbox" id="example-checkbox-id-1" value="some value" name="example-checkbox-name-1">
       <span class="ecl-checkbox__label">Normal checkbox</span>
</label>
```

The reason is a too strict CSS, that only selects the span right after the first input, not taking into account that spring renders a hidden input in between:

```
.ecl-checkbox__input:checked+.ecl-checkbox__label:before {
    background-image: url(../images/checkbox-checked--blue.svg);
}
```

Please bear in mind that when working with frameworks like Spring the structure of the HTML is not always rendered as plain HTML, and that there can be in between elements that make CSS not work.

**Comment by yhuard** [comment]
Hi @dhamaris 

Thank you for your feedback, it's an interesting case showing that we need to decouple the styling from the markup more carefully. We'll try to find a workaround for your issue.

**Comment by yhuard** [comment]
In your case, you can rewrite the CSS selector:


```diff
- .ecl-checkbox__input:checked + .ecl-checkbox__label::before {
+ .ecl-checkbox__input:checked ~ .ecl-checkbox__label::before {
```

as well as 

```diff
- .ecl-checkbox__input:focus + .ecl-checkbox__label::before {
+ .ecl-checkbox__input:focus ~ .ecl-checkbox__label::before {
```

Please note that it can have side effects. If you have multiple `ecl-checkbox__label` elements next to the `ecl-checkbox__input` element, then they will all be checked or focused. But if you always have only one `ecl-checkbox__label` element next to only one `ecl-checkbox__input` within a `<label class="ecl-form-label ecl-checkbox">`, then you should be just fine.

**Comment by dhamaris** [comment]
Thank you for your feedback, in the meantime I added a more specific rule in order to avoid side-effects:

`.ecl-checkbox__input:checked+input[type="hidden"]+.ecl-checkbox__label:before`

As all spring checkbox elements are rendered the same.

**Comment by dhamaris** [comment]
Hello! Long time no see! I reopen this issue as I am finding the same problem related to a too strict css rule (now in ECLv3.6.0), namely:

```
.ecl-checkbox__input:checked+.ecl-checkbox__label .ecl-checkbox__box {
    background: #004494;
    border-color: #004494
}

.ecl-checkbox__input:checked+.ecl-checkbox__label:hover .ecl-checkbox__box {
    background: #002f67;
    border-color: #002f67
}

.ecl-checkbox__input:checked+.ecl-checkbox__label .ecl-checkbox__box--invalid {
    background: #da2131;
    border-color: #da2131
}

.ecl-checkbox__input:checked+.ecl-checkbox__label .ecl-checkbox__icon {
    visibility: visible
}
```
It expects no element between the input and the label, but spring generates a hidden input in between, can you please change it for next releases? 

Thank you

**Comment by planctus** [comment]
Hi @dhamaris, i read also the discussion happened a few years ago, i wasn't yet on ECL, it seems to me that using the generic sibling selector (~) instead of the immediate sibling one (+) as Yannick was already suggesting is still good enough, i don't see a use case where you would have an input and multiple labels, so i don't foresee side effects doing it.
I do wonder if this request is only limited to the checkbox, though, the same approach is used also in the radio component in ECL, if we apply this to the checkbox then i would do the same for radios as well.

**Comment by dhamaris** [comment]
Hi @planctus, I understand that ~ selector opens up another set of risks, in my case I added the following rule in a custom css to avoid the problem:
```

/* Fix related to issue */

.ecl-checkbox__input:checked+input[type="hidden"]+.ecl-checkbox__label .ecl-checkbox__box {
    background: #004494;
    border-color: #004494
}

.ecl-checkbox__input:checked+input[type="hidden"]+.ecl-checkbox__label:hover .ecl-checkbox__box {
    background: #002f67;
    border-color: #002f67
}

.ecl-checkbox__input:checked+input[type="hidden"]+.ecl-checkbox__label .ecl-checkbox__box--invalid {
    background: #da2131;
    border-color: #da2131
}

.ecl-checkbox__input:checked+input[type="hidden"]+.ecl-checkbox__label .ecl-checkbox__icon {
    visibility: visible
}

```
In case of radios, spring does not generate any extra input, so the problem only takes place for checkboxes.
It is up to you to include this in following releases, I already know that it is an issue when working with Spring MVC and I can use the hack myself.
Thank you

**Comment by planctus** [comment]
Hello @dhamaris:
https://github.com/ec-europa/europa-component-library/pull/2800
We've applied this "loose" approach to all the form elements where this was relevant, in the next release you'll have this and you should be able to remove your css. ;)

**Comment by dhamaris** [comment]
Thank you @planctus!
