### ISSUE TITLE
ECL Browsers support

### ISSUE THREAD

**Issue by Massimiliano2179** [ec-europa/europa-component-library#729]
### Expected behavior
What is the full browsers support of the ECL?
Which version of Chrome?Opera?
Has it been tested on Android, IOS, Linux or others?

### Actual behavior
ECL is tested on Firefox54, IE 11, Safari 11

**Comment by yhuard** [comment]
Hi @Massimiliano2179
 
The browsers we support are defined in https://github.com/ec-europa/europa-component-library/blob/adff86b26f5e77b1b9dbb96786e6d0b2bf6f6392/browserslist (it's a config file passed to Autoprefixer and other tools), which translates to http://browserl.ist/?q=%3E+1%25%2C+last+2+versions%2C+not+ie+10%2C+not+ie_mob+10%2C+not+safari+%3C+10 

Besides that, we have tests running on IE 11 (Windows 7), FF 54 (Windows 7), Safari 11 (macOS 10.12) and Chrome 60 (Windows 10), as defined here: https://github.com/ec-europa/europa-component-library/blob/fc6f726c2b325c0b005b86498170015a1e4035e0/test/functional/utils/capabilities.js (selenium capabilities)

We don't have tests for iOS / Android / Linux yet but this is something we can look into.

Have a nice day!
