### ISSUE TITLE
Please check the checkbox component behaviour

### ISSUE THREAD

**Issue by Massimiliano2179** [ec-europa/europa-component-library#733]
### Expected behavior
It is supposed to click on the checkbox to activate/deactivate
### Actual behavior
If you click anywhere on the line of the checkbox (not only in the box) it activate/deactivate
### Steps to reproduce the issue
https://ec-europa.github.io/europa-component-library/ec/components/detail/ec-component-form-checkbox

**Comment by degliwe** [comment]
Thank you for your report.
This is the expected behavior.
http://uxmovement.com/forms/why-your-checkboxes-need-to-have-label-tags/
