### ISSUE TITLE
Language overlay component not changing label in header (.ecl-lang-select-sites__label)

### ISSUE THREAD

**Issue by Massimiliano2179** [ec-europa/europa-component-library#740]
### Expected behavior
After choosing a language and closing the overlay language select panel the "language label" visible to the user in the header should change too.
(Eg. From English to Spanish > User should see in the header the spanish label)
(.ecl-lang-select-sites__label)
 
### Actual behavior
At moment when changing language the english label remain active both in the overlay panel and in the header visible to user

### Steps to reproduce the issue
https://ec-europa.github.io/europa-component-library/ec/components/detail/ec-component-language-list--overlay

**Comment by yhuard** [comment]
Hi @Massimiliano2179,

After choosing a language, the user should get redirected to the translated page. Languages are links, not buttons. There's no dynamic behavior to expect here.
