### ISSUE TITLE
Smooth scroll on inpage navigations

### ISSUE THREAD

**Issue by Phury** [ec-europa/europa-component-library#845]
We are currently using the inpage navigation but also implemented smooth scroll as it is requested by our client. To do so we override the click event of `ecl-inpage-navigation__link` as follows:

```
document.activeElement.blur();
var sectionTop = $('#section' + sectionNumber).offset().top;
if (/Edge/.test(navigator.userAgent)) { // Edge has trouble with animated scroll
	$(window).scrollTop(sectionTop);
} else {
	$('html').animate({
		scrollTop: sectionTop
	}, 1000);
}
```

I have noticed that inpage navigation component uses `gumshoe.js` and that it is compatible with `smoothscroll.js` of the same developer.
I believe adding that behaviour is quite straigthforward in component `\src\generic\generic-component-inpage-navigation\generic-component-inpage-navigation.js` but I am not sure how this feature could be activated/deactivadted

### Expected behavior

When I click on `ecl-inpage-navigation__link`  with href `#section-1` and smooth scroll is activated
Then I navigate to to block with id `section-1` smoothly

### Actual behavior

When I click on `ecl-inpage-navigation__link`  with href `#section-1`
Then I jump to to block with id `section-1` 

### Steps to reproduce the issue

Go to inpage navigation and clik on any link.

**Comment by degliwe** [comment]
Thank you for your report @Phury 
From what I understand you are trying to alter the behavior of ECL components.
The point of ECL component is that they behave the same on all the EC sites.

If you want to make a case for smoothscroll, I would then suggest you to get in touch with the design team and convince them to update the specs for this component.
