### ISSUE TITLE
Scrollspy when components are added to the page dynamically

### ISSUE THREAD

**Issue by phatarhs** [ec-europa/europa-component-library#846]
We are currently using the inpage navigation for one of our clients and if we add dynamic content to the page, the scrollspy component does not show the correct headers highlighted anymore. I'm suspecting the positions do not get recomputed dynamically. We are using the following to initialize the component:

```
ECL.navigationInpages();
```

### Expected behavior

When adding dynamic content to a page containing an inpage navigation with scrollspy
Then scrollspy still displays the correct links highlighted when I am scrolling up or down the different sections of my page

### Actual behavior

When adding dynamic content to a page containing an inpage navigation with scrollspy
Then scrollspy does not show the correct links highlighted when I am scrolling up or down the different sections of my page

### Steps to reproduce the issue

Create a inpage navigation as presented here https://ec-europa.github.io/europa-component-library/ec/components/detail/ec-component-inpage-navigation
Add dynamic elements to the page (you can do this through the console for instance)
Scroll spy will not show the correct link highlighted anymore.

**Comment by degliwe** [comment]
Thanks for the report @phatarhs 
You are right, this feature isn't supported at the moment.
We are using https://github.com/cferdinandi/gumshoe for the scrollspy.
As you can see here https://github.com/ec-europa/europa-component-library/blob/v1/src/generic/generic-component-inpage-navigation/generic-component-inpage-navigation.js
I see that gumshoe allow for a recomputation of the document height https://github.com/cferdinandi/gumshoe#setdistances

We are working on the V2 of ECL and we can take this extra requirement on board for the version 2 of this component.
I can't give you any time estimate for this.
