### ISSUE TITLE
[RFC] Radio button - INNO-1305

### ISSUE THREAD

**Issue by yhuard** [ec-europa/europa-component-library#996]
# Component: Radio button

## Design 

Design Specs: https://webgate.ec.europa.eu/CITnet/confluence/pages/viewpage.action?spaceKey=NEXTEUROPA&title=Radio+buttons+-+Design+specifications

The specs only show 1 radio button with its associated label. IMHO the radio button only makes sense if it is part of a group, and this group has a label/heading itself.

### Questions

- do we all agree to make this implementation? (radio group + radio buttons, instead of only radio buttons)

## Expected content & properties

The radio group can have:
- `invalid` (boolean)
- error message (mixed) / or is it a child?

The radio heading contains:
- a body (mixed): only text in most cases but may be more complex than just text (icons, figures, etc.)

Each radio button comes with:
- a `label` (mixed): only text in most cases but may be more complex than just text (icons, figures, etc.)
- `disabled` (boolean)
- `checked` (boolean)
- `name` (string)
- `id` (string)
- `value` (string)
- `required` (boolean)

### Questions

- do you see other properties we should take into account?
- can we validate the names of the properties?

## ECL Initial Implementation Proposal (EIIP)

The JSX code showing the big picture:

```jsx
<RadioGroup invalid>
  <RadioHeading>Heading for the radio group</RadioHeading>
  <RadioButton name="group1" id="radio1" value="value1" checked>My radio button</RadioButton>
  <RadioButton name="group1" id="radio2" value="value2">My other radio button</RadioButton>
  <RadioButton name="group1" id="radio3" value="value3" disabled>My disabled radio button</RadioButton>
</RadioGroup>
```

`<RadioGroup>` being a `<fieldset>`, `<RadioHeading>` a `<legend>`.

`<RadioButton>` can be a `<label>` enclosing the `<input>` and everything that's needed for the label, or an `<input>` with an ID followed by a `<label>` with `for`.

HTML overview:

```html
<fieldset> 
  <legend>Heading for the radio group</legend> 
  <ul> 
    <li>
      <input type="radio" name="group1" id="radio1" value="value1" checked />
      <label for="radio1">My radio button</label>
    </li> 
    <li>
      <input type="radio" name="group1" id="radio2" value="value2" />
      <label for="radio2">My other radio button</label>
    </li> 
    <li>
      <input type="radio" name="group1" id="radio3" value="value3" disabled />
      <label for="radio3">My disabled radio button</label>
    </li> 
  </ul> 
</fieldset> 
```

About this proposal: `<input>`s and `<label>`s are encapsulated in list items. It gives us isolation between each radio button which can be good and bad. IMHO it also makes the code more readable.

Another possible implementation, as stated earlier, is achieved by putting the `<input>` element inside the `<label>`. This way, can spare some headaches with IDs but we can't style the `<label>` depending on the `<input>`'s attributes. We could still encapsulate the "body" of the `<label>` within a span to achieve the same result, e.g. `<label><input type="radio"...><span>My label styled depending on the input</span></label>`.

Other implementations:

- alternative 1

```html
<fieldset> 
  <legend>Heading for the radio group</legend> 
  <ul> 
    <li>
      <label>
        <input type="radio" name="group1" value="value1" checked />
        My radio button
      </label>
    </li> 
    <li>
      <label>
        <input type="radio" name="group1" value="value2" />
        My other radio button
      </label>
    </li> 
    <li>
      <label>
        <input type="radio" name="group1" value="value3" disabled />
        My disabled radio button
      </label>
    </li> 
  </ul> 
</fieldset> 
```

- alternative 2

```html
<fieldset> 
  <legend>Heading for the radio group</legend> 
  <label>
    <input type="radio" name="group1" value="value1" checked />
    My radio button
  </label>
  <label>
    <input type="radio" name="group1" value="value2" />
    My other radio button
  </label>
  <label>
    <input type="radio" name="group1" value="value3" disabled />
    My disabled radio button
  </label>
</fieldset> 
```

- alternative 3

```html
<fieldset> 
  <legend>Heading for the radio group</legend>
  <div>
    <label>
      <input type="radio" name="group1" value="value1" checked />
      My radio button
    </label>
    <label>
      <input type="radio" name="group1" value="value2" />
      My other radio button
    </label>
    <label>
      <input type="radio" name="group1" value="value3" disabled />
      My disabled radio button
    </label>
  </div>
</fieldset> 
```

etc.

### Questions

- to use lists or not to use lists? 
- `<input /><label />` or `<label><input /></label>`?

## Resources

- https://www.w3.org/WAI/tutorials/forms/grouping/

>  Radio button groups should always be grouped using `<fieldset>`.

## Sources of inspiration

- https://atlaskit.atlassian.com/packages/core/radio - `<label><input /></label>`
- https://www.carbondesignsystem.com/components/radio-button/code - `<input /><label />`
- https://getbootstrap.com/docs/4.2/components/forms/#checkboxes-and-radios - `<input /><label />`
- https://www.lightningdesignsystem.com/components/radio-group/ - `<input /><label />`
- https://materializecss.com/radio-buttons.html - `<label><input /></label>`
- https://material-components.github.io/material-components-web-catalog/#/component/radio  - `<input /><label />`
- https://styleguide.github.com/primer/components/forms/#checkboxes-and-radios - `<label><input /></label>`
- https://baseui.design/components/radio/ - `<label><input /></label>`
- https://polaris.shopify.com/components/forms/radio-button - `<label><input /></label>`
- https://ant.design/components/radio/ - `<label><input /></label>`
- https://developer.microsoft.com/en-us/fabric#/components/choicegroup - `<input /><label />`
- https://clarity.design/documentation/radio - `<input /><label />`
- https://bulma.io/documentation/form/radio/ - `<label><input /></label>`
- https://design-system.service.gov.uk/components/radios/ - `<input /><label />`

Counts:
- `<label><input /></label>`: 7
- `<input /><label />`: 7

**Comment by yhuard** [comment]
The case for adjacent `<label>` and `<input>`: https://www.w3.org/WAI/tutorials/forms/labels/ 

> Generally, explicit labels [with ID, Ed] are better supported by assistive technology.

**Comment by degliwe** [comment]
> Do we all agree to make this implementation? (radio group + radio buttons, instead of only radio buttons)

Yes

> can we validate the names of the properties?

Yes minus the article "a" in front of body and label

> to use lists or not to use lists?

I don't see the value of using lists here. except that it makes the markup unnecessary complex

> `<input /><label />` or `<label><input /></label>`?

`<label><input /></label>` seems the shortest less ambiguous option

**Comment by yhuard** [comment]
> `<label><input /></label>` seems the shortest less ambiguous option

https://www.w3.org/TR/WCAG20-TECHS/H44.html seems to favour the explicit way (`<input /><label />`)

now, both solutions are valid but I'd require that if we go for `<label><input /></label>`, we still use `for` and `id` attributes

**Comment by yhuard** [comment]
After analysing the aforementioned existing design systems, I've found out that both solutions are evenly used:
- `<label><input /></label>`: 7 times
- `<input /><label />`: 7 times

**Comment by yhuard** [comment]
More about the label: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Clabel%3E_element

> Note that a widget can be nested inside its <label> element, like so:
```html
<label for="name">
  Name: <input type="text" id="name" name="user_name">
</label>
```
> Even in such cases however, **it is considered best practice to set the for attribute because some assistive technologies do not understand implicit relationships between labels and widgets**.

**Comment by emeryro** [comment]
Firstly, I agree that the list is not necessary here (only add extra markup).
Then, why do we have a `required` property on a single radio button? Shouldn't it be on the radio group?
Lastly, I'm in favor of `<input /><label />`, as it offers more flexibility for styling (no need to add extra span), and that's also the way it is done by A11Y and W3C.

**Comment by yhuard** [comment]
@emeryro regarding the `required` property:

> For radio buttons, the required attribute is satisfied if any of the radio buttons in the group is selected.

> To avoid confusion as to whether a radio button group is required or not, authors are encouraged to specify the attribute on all the radio buttons in a group. Indeed, in general, authors are encouraged to avoid having radio button groups that do not have any initially checked controls in the first place, as this is a state that the user cannot return to, and is therefore generally considered a poor user interface.

— https://www.w3.org/TR/html5/forms.html#the-required-attribute

Now, indeed, in the JSX implementation we could define a `required` attribute on the `<RadioGroup>` and then implicitly apply this attribute on all the `<input type="radio" />`. But I prefer when it's explicit and when developers actually know what they're doing, so I'd not support this idea. 😅

**Comment by emeryro** [comment]
I find it weird to have only one radio as required (as in their example), and I guess we agree that it should be all required or nothing required (in a single radio group).
Then, I don't mind if we keep the property is in the radio elements instead of the group

**Comment by yhuard** [comment]
I agree it's confusing and I'd rather see "all or nothing"

**Comment by degliwe** [comment]
It seems that we reached a consensus here.
Please approve (like this comment) so that we move forward or add extra comments.
