### ISSUE TITLE
[RFC] File component - INNO-1320

### ISSUE THREAD

**Issue by yhuard** [ec-europa/europa-component-library#998]
This is a RFC an on Improvement Proposal.

## How can we improve the markup?

IMHO more attributes should be used on the download links in the file component. The current implementation for the main Download link looks like this:

```html
<a href="/path/to/file.pdf" class="[...]">
  <span class="[...]">Download</span>
  <svg focusable="false" aria-hidden="true" class="[...]">
    <use xlink:href="/static/media/icons.cbfd6efe.svg#ui--download"></use>
  </svg>
</a>
```

And the links to the translations (with the label) look like that:

```html
<div class="[...]">
  <div class="[...]">español</div>
  <div class="[...]">(15.8 MB - PDF)</div>
</div>
<a href="/path/to/file.pdf" class="[...]">
  <span class="[...]">Download</span> 
  <svg focusable="false" aria-hidden="true" class="[...]">
    <use xlink:href="/static/media/icons.cbfd6efe.svg#ui--download"></use>
  </svg>
</a>
```

https://v2--europa-component-library.netlify.com/ec/components/file/code/

Here are the attributes we could use:

On the links:

- `download`: to make the browser download the file (instead of opening it)

> The download attribute, if present, indicates that the author intends the hyperlink to be used for downloading a resource. The attribute may have a value; the value, if any, specifies the default file name that the author recommends for use in labeling the resource in a local file system. There are no restrictions on allowed values, but authors are cautioned that most file systems have limitations with regard to what punctuation is supported in file names, and user agents are likely to adjust file names accordingly.

— https://www.w3.org/TR/2017/REC-html52-20171214/links.html#element-attrdef-a-download

- `hreflang`: to tell the browser in which language the document will be

> The hreflang attribute on a elements that create hyperlinks, if present, gives the language of the linked resource. It is purely advisory. The value must be a valid BCP 47 language tag. [BCP47] User agents must not consider this attribute authoritative — upon fetching the resource, user agents must use only language information associated with the resource to determine its language, not metadata included in the link to the resource.

— https://www.w3.org/TR/2017/REC-html52-20171214/links.html#element-attrdef-a-hreflang

On the label:
- `lang`: to specify the language used in the div, e.g. `español` is written in spanish  — https://www.w3schools.com/tags/att_global_lang.asp

## What it would look like?

Here are the 2 HTML snippets from before, improved:

```html
<a href="/path/to/file.pdf" class="[...]" download>
  <span class="[...]">Download</span>
  <svg focusable="false" aria-hidden="true" class="[...]">
    <use xlink:href="/static/media/icons.cbfd6efe.svg#ui--download"></use>
  </svg>
</a>
```

```html
<div class="[...]">
  <div class="[...]" lang="es">español</div>
  <div class="[...]">(15.8 MB - PDF)</div>
</div>
<a href="/path/to/file-es.pdf" hreflang="es" class="[...]" download>
  <span class="[...]">Download</span> 
  <svg focusable="false" aria-hidden="true" class="[...]">
    <use xlink:href="/static/media/icons.cbfd6efe.svg#ui--download"></use>
  </svg>
</a>
```

## Questions

- Do you agree to add these attributes?
- Can you think of other attributes we could use to improve the markup? 
  - Type? https://www.w3.org/TR/2017/REC-html52-20171214/links.html#element-attrdef-a-type

## Resources

- https://www.w3.org/TR/2017/REC-html52-20171214/links.html#links
- https://www.w3schools.com/tags/att_a_download.asp
- https://www.w3schools.com/howto/howto_html_download_link.asp
- https://www.w3schools.com/tags/att_a_hreflang.asp

**Comment by emeryro** [comment]
Let's take them one by one:

- `lang`: seems like a natural improvement. I don't know how widely this attribute is supported by screen readers, but it may also be used later to enhance display via CSS.
- `hreflang`: I don't see it in your markup example, but it is indeed legit
- `download` is the tricky one. On one side, it make sense to add it for a download button, on the other side it will enforce a behavior to the user. I personaly prefer to preview files in the browser first, and really download them later if needed, but it is always possible to do it by opening the link in a new tab. So ok, we can make a try with it, and see the reactions.

**Comment by yhuard** [comment]
I've updated the second improved example with `hreflang` ✅ I don't think it adds any value if the target of the link is in the same language as the current document. To be checked.

Regarding the `download` attribute: to me, it all boils down to expectations. A link with a "download" label lets the user think (and expect) that when he or she clicks on it, the download will start. I, personally, don't expect the file to pop-up in a new tab or worse, in the same tab. Don't you agree?

**Comment by degliwe** [comment]
Overall, I like the proposal.
I agree 100% that we have to improve our markup and make use of all the well supported and useful  attributes, across all our components (ex:language selector) 
What you suggest seems like a good start.

**Comment by yhuard** [comment]
We make use of the 3 attributes (`lang`, `hreflang` and `download`). Deal?
Any other attribute to add or do we close this RFC and implement it?

**Comment by yhuard** [comment]
Proposal approved ✅
